import { useEffect } from "react";

// Registers the service worker generated by vite-plugin-pwa. The virtual module
// only exists in the client build, so we dynamically import it inside an effect
// (which never runs during SSR). With registerType "autoUpdate", a new SW takes
// over automatically on the next navigation/visit.
export function PWARegister() {
	useEffect(() => {
		import("virtual:pwa-register")
			.then(({ registerSW }) => {
				registerSW({ immediate: true });
			})
			.catch(() => {
				// SW registration is best-effort; ignore failures (e.g. unsupported browser).
			});
	}, []);

	return null;
}
