// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: applications.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveApplication = `-- name: ApproveApplication :one
UPDATE author_applications SET
    status = 'approved',
    reviewed_at = NOW(),
    reviewed_by = $2,
    review_notes = $3
WHERE id = $1
RETURNING id, clerk_id, full_name, email, bio, experience, status, submitted_at, reviewed_at, reviewed_by, review_notes
`

type ApproveApplicationParams struct {
	ID          pgtype.UUID
	ReviewedBy  pgtype.Text
	ReviewNotes pgtype.Text
}

func (q *Queries) ApproveApplication(ctx context.Context, arg ApproveApplicationParams) (AuthorApplication, error) {
	row := q.db.QueryRow(ctx, approveApplication, arg.ID, arg.ReviewedBy, arg.ReviewNotes)
	var i AuthorApplication
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.FullName,
		&i.Email,
		&i.Bio,
		&i.Experience,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.ReviewNotes,
	)
	return i, err
}

const createAuthorApplication = `-- name: CreateAuthorApplication :one
INSERT INTO author_applications (clerk_id, full_name, email, bio, experience)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, clerk_id, full_name, email, bio, experience, status, submitted_at, reviewed_at, reviewed_by, review_notes
`

type CreateAuthorApplicationParams struct {
	ClerkID    string
	FullName   string
	Email      string
	Bio        string
	Experience string
}

func (q *Queries) CreateAuthorApplication(ctx context.Context, arg CreateAuthorApplicationParams) (AuthorApplication, error) {
	row := q.db.QueryRow(ctx, createAuthorApplication,
		arg.ClerkID,
		arg.FullName,
		arg.Email,
		arg.Bio,
		arg.Experience,
	)
	var i AuthorApplication
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.FullName,
		&i.Email,
		&i.Bio,
		&i.Experience,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.ReviewNotes,
	)
	return i, err
}

const getAuthorApplication = `-- name: GetAuthorApplication :one
SELECT id, clerk_id, full_name, email, bio, experience, status, submitted_at, reviewed_at, reviewed_by, review_notes FROM author_applications WHERE id = $1
`

func (q *Queries) GetAuthorApplication(ctx context.Context, id pgtype.UUID) (AuthorApplication, error) {
	row := q.db.QueryRow(ctx, getAuthorApplication, id)
	var i AuthorApplication
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.FullName,
		&i.Email,
		&i.Bio,
		&i.Experience,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.ReviewNotes,
	)
	return i, err
}

const getAuthorApplicationByClerkID = `-- name: GetAuthorApplicationByClerkID :one
SELECT id, clerk_id, full_name, email, bio, experience, status, submitted_at, reviewed_at, reviewed_by, review_notes FROM author_applications
WHERE clerk_id = $1
ORDER BY submitted_at DESC
LIMIT 1
`

func (q *Queries) GetAuthorApplicationByClerkID(ctx context.Context, clerkID string) (AuthorApplication, error) {
	row := q.db.QueryRow(ctx, getAuthorApplicationByClerkID, clerkID)
	var i AuthorApplication
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.FullName,
		&i.Email,
		&i.Bio,
		&i.Experience,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.ReviewNotes,
	)
	return i, err
}

const listPendingApplications = `-- name: ListPendingApplications :many
SELECT id, clerk_id, full_name, email, bio, experience, status, submitted_at, reviewed_at, reviewed_by, review_notes FROM author_applications
WHERE status = 'pending'
ORDER BY submitted_at ASC
`

func (q *Queries) ListPendingApplications(ctx context.Context) ([]AuthorApplication, error) {
	rows, err := q.db.Query(ctx, listPendingApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthorApplication
	for rows.Next() {
		var i AuthorApplication
		if err := rows.Scan(
			&i.ID,
			&i.ClerkID,
			&i.FullName,
			&i.Email,
			&i.Bio,
			&i.Experience,
			&i.Status,
			&i.SubmittedAt,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.ReviewNotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectApplication = `-- name: RejectApplication :one
UPDATE author_applications SET
    status = 'rejected',
    reviewed_at = NOW(),
    reviewed_by = $2,
    review_notes = $3
WHERE id = $1
RETURNING id, clerk_id, full_name, email, bio, experience, status, submitted_at, reviewed_at, reviewed_by, review_notes
`

type RejectApplicationParams struct {
	ID          pgtype.UUID
	ReviewedBy  pgtype.Text
	ReviewNotes pgtype.Text
}

func (q *Queries) RejectApplication(ctx context.Context, arg RejectApplicationParams) (AuthorApplication, error) {
	row := q.db.QueryRow(ctx, rejectApplication, arg.ID, arg.ReviewedBy, arg.ReviewNotes)
	var i AuthorApplication
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.FullName,
		&i.Email,
		&i.Bio,
		&i.Experience,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.ReviewNotes,
	)
	return i, err
}
