// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artists.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArtist = `-- name: CreateArtist :one
INSERT INTO artists (
    name, bio, genres, image_url, website_url, spotify_url, instagram_url,
    bandcamp_url, youtube_url, hometown_city, hometown_state,
    owner_user_id, source, is_claimed
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11,
    $12, 'user', TRUE
)
ON CONFLICT (LOWER(TRIM(name))) DO UPDATE SET
    bio = EXCLUDED.bio,
    genres = EXCLUDED.genres,
    image_url = COALESCE(NULLIF(EXCLUDED.image_url, ''), artists.image_url),
    website_url = EXCLUDED.website_url,
    spotify_url = EXCLUDED.spotify_url,
    instagram_url = EXCLUDED.instagram_url,
    bandcamp_url = EXCLUDED.bandcamp_url,
    youtube_url = EXCLUDED.youtube_url,
    hometown_city = EXCLUDED.hometown_city,
    hometown_state = EXCLUDED.hometown_state,
    owner_user_id = EXCLUDED.owner_user_id,
    is_claimed = TRUE,
    updated_at = NOW()
WHERE artists.owner_user_id IS NULL OR artists.owner_user_id = EXCLUDED.owner_user_id
RETURNING id, name, bio, genres, image_url, website_url, spotify_url, instagram_url, bandcamp_url, youtube_url, hometown_city, hometown_state, owner_user_id, source, external_id, is_claimed, created_at, updated_at
`

type CreateArtistParams struct {
	Name          string
	Bio           pgtype.Text
	Genres        []string
	ImageUrl      pgtype.Text
	WebsiteUrl    pgtype.Text
	SpotifyUrl    pgtype.Text
	InstagramUrl  pgtype.Text
	BandcampUrl   pgtype.Text
	YoutubeUrl    pgtype.Text
	HometownCity  pgtype.Text
	HometownState pgtype.Text
	OwnerUserID   pgtype.UUID
}

// Self-serve create OR claim-an-existing-stub by name. On conflict the row is
// updated and ownership set, but ONLY when it's unowned or already owned by the
// same user; a name owned by someone else updates zero rows (RETURNING is empty,
// surfaced as a conflict by the handler).
func (q *Queries) CreateArtist(ctx context.Context, arg CreateArtistParams) (Artist, error) {
	row := q.db.QueryRow(ctx, createArtist,
		arg.Name,
		arg.Bio,
		arg.Genres,
		arg.ImageUrl,
		arg.WebsiteUrl,
		arg.SpotifyUrl,
		arg.InstagramUrl,
		arg.BandcampUrl,
		arg.YoutubeUrl,
		arg.HometownCity,
		arg.HometownState,
		arg.OwnerUserID,
	)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.Genres,
		&i.ImageUrl,
		&i.WebsiteUrl,
		&i.SpotifyUrl,
		&i.InstagramUrl,
		&i.BandcampUrl,
		&i.YoutubeUrl,
		&i.HometownCity,
		&i.HometownState,
		&i.OwnerUserID,
		&i.Source,
		&i.ExternalID,
		&i.IsClaimed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArtist = `-- name: DeleteArtist :exec
DELETE FROM artists WHERE id = $1
`

// event_artists rows cascade away via the FK ON DELETE CASCADE.
func (q *Queries) DeleteArtist(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteArtist, id)
	return err
}

const getArtist = `-- name: GetArtist :one
SELECT id, name, bio, genres, image_url, website_url, spotify_url, instagram_url, bandcamp_url, youtube_url, hometown_city, hometown_state, owner_user_id, source, external_id, is_claimed, created_at, updated_at FROM artists WHERE id = $1
`

func (q *Queries) GetArtist(ctx context.Context, id pgtype.UUID) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtist, id)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.Genres,
		&i.ImageUrl,
		&i.WebsiteUrl,
		&i.SpotifyUrl,
		&i.InstagramUrl,
		&i.BandcampUrl,
		&i.YoutubeUrl,
		&i.HometownCity,
		&i.HometownState,
		&i.OwnerUserID,
		&i.Source,
		&i.ExternalID,
		&i.IsClaimed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtistByName = `-- name: GetArtistByName :one
SELECT id, name, bio, genres, image_url, website_url, spotify_url, instagram_url, bandcamp_url, youtube_url, hometown_city, hometown_state, owner_user_id, source, external_id, is_claimed, created_at, updated_at FROM artists WHERE LOWER(TRIM(name)) = LOWER(TRIM($1::text))
`

func (q *Queries) GetArtistByName(ctx context.Context, name string) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtistByName, name)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.Genres,
		&i.ImageUrl,
		&i.WebsiteUrl,
		&i.SpotifyUrl,
		&i.InstagramUrl,
		&i.BandcampUrl,
		&i.YoutubeUrl,
		&i.HometownCity,
		&i.HometownState,
		&i.OwnerUserID,
		&i.Source,
		&i.ExternalID,
		&i.IsClaimed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkEventArtist = `-- name: LinkEventArtist :exec
INSERT INTO event_artists (event_id, artist_id, position, is_headliner)
VALUES ($1, $2, $3, $4)
ON CONFLICT (event_id, artist_id) DO NOTHING
`

type LinkEventArtistParams struct {
	EventID     pgtype.UUID
	ArtistID    pgtype.UUID
	Position    int32
	IsHeadliner bool
}

func (q *Queries) LinkEventArtist(ctx context.Context, arg LinkEventArtistParams) error {
	_, err := q.db.Exec(ctx, linkEventArtist,
		arg.EventID,
		arg.ArtistID,
		arg.Position,
		arg.IsHeadliner,
	)
	return err
}

const listArtistsByLocation = `-- name: ListArtistsByLocation :many
SELECT DISTINCT a.id, a.name, a.bio, a.genres, a.image_url, a.website_url, a.spotify_url, a.instagram_url, a.bandcamp_url, a.youtube_url, a.hometown_city, a.hometown_state, a.owner_user_id, a.source, a.external_id, a.is_claimed, a.created_at, a.updated_at
FROM artists a
JOIN event_artists ea ON ea.artist_id = a.id
JOIN events e ON e.id = ea.event_id
WHERE e.start_time >= NOW()
AND ST_DWithin(
    ST_SetSRID(ST_MakePoint(e.longitude, e.latitude), 4326)::geography,
    ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography,
    $3::float
)
AND ($4::text IS NULL OR $4::text = ANY(a.genres))
ORDER BY a.name ASC
`

type ListArtistsByLocationParams struct {
	Lng          float64
	Lat          float64
	RadiusMeters float64
	Genre        pgtype.Text
}

// Artists with an upcoming event near a location (optionally filtered by genre).
// "Playing in the area" — only artists with a future show in range appear.
func (q *Queries) ListArtistsByLocation(ctx context.Context, arg ListArtistsByLocationParams) ([]Artist, error) {
	rows, err := q.db.Query(ctx, listArtistsByLocation,
		arg.Lng,
		arg.Lat,
		arg.RadiusMeters,
		arg.Genre,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Bio,
			&i.Genres,
			&i.ImageUrl,
			&i.WebsiteUrl,
			&i.SpotifyUrl,
			&i.InstagramUrl,
			&i.BandcampUrl,
			&i.YoutubeUrl,
			&i.HometownCity,
			&i.HometownState,
			&i.OwnerUserID,
			&i.Source,
			&i.ExternalID,
			&i.IsClaimed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtistsByOwner = `-- name: ListArtistsByOwner :many
SELECT id, name, bio, genres, image_url, website_url, spotify_url, instagram_url, bandcamp_url, youtube_url, hometown_city, hometown_state, owner_user_id, source, external_id, is_claimed, created_at, updated_at FROM artists WHERE owner_user_id = $1 ORDER BY name ASC
`

func (q *Queries) ListArtistsByOwner(ctx context.Context, ownerUserID pgtype.UUID) ([]Artist, error) {
	rows, err := q.db.Query(ctx, listArtistsByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Bio,
			&i.Genres,
			&i.ImageUrl,
			&i.WebsiteUrl,
			&i.SpotifyUrl,
			&i.InstagramUrl,
			&i.BandcampUrl,
			&i.YoutubeUrl,
			&i.HometownCity,
			&i.HometownState,
			&i.OwnerUserID,
			&i.Source,
			&i.ExternalID,
			&i.IsClaimed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtistsForEvent = `-- name: ListArtistsForEvent :many
SELECT a.id, a.name, a.bio, a.genres, a.image_url, a.website_url, a.spotify_url, a.instagram_url, a.bandcamp_url, a.youtube_url, a.hometown_city, a.hometown_state, a.owner_user_id, a.source, a.external_id, a.is_claimed, a.created_at, a.updated_at
FROM artists a
JOIN event_artists ea ON ea.artist_id = a.id
WHERE ea.event_id = $1
ORDER BY ea.is_headliner DESC, ea.position ASC, a.name ASC
`

func (q *Queries) ListArtistsForEvent(ctx context.Context, eventID pgtype.UUID) ([]Artist, error) {
	rows, err := q.db.Query(ctx, listArtistsForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Bio,
			&i.Genres,
			&i.ImageUrl,
			&i.WebsiteUrl,
			&i.SpotifyUrl,
			&i.InstagramUrl,
			&i.BandcampUrl,
			&i.YoutubeUrl,
			&i.HometownCity,
			&i.HometownState,
			&i.OwnerUserID,
			&i.Source,
			&i.ExternalID,
			&i.IsClaimed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingEventsForArtist = `-- name: ListUpcomingEventsForArtist :many
SELECT e.id, e.external_id, e.source, e.title, e.description, e.venue_name, e.address, e.city, e.state, e.zip, e.latitude, e.longitude, e.start_time, e.end_time, e.image_url, e.ticket_url, e.price_min, e.price_max, e.submitted_by, e.created_at, e.updated_at, e.manually_edited, e.venue_id, e.categories, e.series_id, e.is_free, e.is_featured, e.featured_at, e.featured_by, e.genre
FROM events e
JOIN event_artists ea ON ea.event_id = e.id
WHERE ea.artist_id = $1 AND e.start_time >= NOW()
ORDER BY e.start_time ASC
`

func (q *Queries) ListUpcomingEventsForArtist(ctx context.Context, artistID pgtype.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, listUpcomingEventsForArtist, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Source,
			&i.Title,
			&i.Description,
			&i.VenueName,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Latitude,
			&i.Longitude,
			&i.StartTime,
			&i.EndTime,
			&i.ImageUrl,
			&i.TicketUrl,
			&i.PriceMin,
			&i.PriceMax,
			&i.SubmittedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ManuallyEdited,
			&i.VenueID,
			&i.Categories,
			&i.SeriesID,
			&i.IsFree,
			&i.IsFeatured,
			&i.FeaturedAt,
			&i.FeaturedBy,
			&i.Genre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArtist = `-- name: UpdateArtist :one
UPDATE artists SET
    name = $2,
    bio = $3,
    genres = $4,
    image_url = $5,
    website_url = $6,
    spotify_url = $7,
    instagram_url = $8,
    bandcamp_url = $9,
    youtube_url = $10,
    hometown_city = $11,
    hometown_state = $12,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, bio, genres, image_url, website_url, spotify_url, instagram_url, bandcamp_url, youtube_url, hometown_city, hometown_state, owner_user_id, source, external_id, is_claimed, created_at, updated_at
`

type UpdateArtistParams struct {
	ID            pgtype.UUID
	Name          string
	Bio           pgtype.Text
	Genres        []string
	ImageUrl      pgtype.Text
	WebsiteUrl    pgtype.Text
	SpotifyUrl    pgtype.Text
	InstagramUrl  pgtype.Text
	BandcampUrl   pgtype.Text
	YoutubeUrl    pgtype.Text
	HometownCity  pgtype.Text
	HometownState pgtype.Text
}

func (q *Queries) UpdateArtist(ctx context.Context, arg UpdateArtistParams) (Artist, error) {
	row := q.db.QueryRow(ctx, updateArtist,
		arg.ID,
		arg.Name,
		arg.Bio,
		arg.Genres,
		arg.ImageUrl,
		arg.WebsiteUrl,
		arg.SpotifyUrl,
		arg.InstagramUrl,
		arg.BandcampUrl,
		arg.YoutubeUrl,
		arg.HometownCity,
		arg.HometownState,
	)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.Genres,
		&i.ImageUrl,
		&i.WebsiteUrl,
		&i.SpotifyUrl,
		&i.InstagramUrl,
		&i.BandcampUrl,
		&i.YoutubeUrl,
		&i.HometownCity,
		&i.HometownState,
		&i.OwnerUserID,
		&i.Source,
		&i.ExternalID,
		&i.IsClaimed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertArtistStub = `-- name: UpsertArtistStub :one
INSERT INTO artists (name, source, external_id)
VALUES ($1, $2, $3)
ON CONFLICT (LOWER(TRIM(name))) DO UPDATE SET updated_at = NOW()
RETURNING id, name, bio, genres, image_url, website_url, spotify_url, instagram_url, bandcamp_url, youtube_url, hometown_city, hometown_state, owner_user_id, source, external_id, is_claimed, created_at, updated_at
`

type UpsertArtistStubParams struct {
	Name       string
	Source     string
	ExternalID pgtype.Text
}

// Dedup-by-name upsert for scraper-recovered lineup artists. Never clobbers an
// existing (possibly user-owned) row's profile fields.
func (q *Queries) UpsertArtistStub(ctx context.Context, arg UpsertArtistStubParams) (Artist, error) {
	row := q.db.QueryRow(ctx, upsertArtistStub, arg.Name, arg.Source, arg.ExternalID)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.Genres,
		&i.ImageUrl,
		&i.WebsiteUrl,
		&i.SpotifyUrl,
		&i.InstagramUrl,
		&i.BandcampUrl,
		&i.YoutubeUrl,
		&i.HometownCity,
		&i.HometownState,
		&i.OwnerUserID,
		&i.Source,
		&i.ExternalID,
		&i.IsClaimed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
