// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: beverage_checkins.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkInBeverage = `-- name: CheckInBeverage :one
INSERT INTO beverage_checkins (user_id, beverage_id, user_latitude, user_longitude)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, beverage_id, checkin_date) DO NOTHING
RETURNING id, user_id, beverage_id, checkin_date, user_latitude, user_longitude, created_at
`

type CheckInBeverageParams struct {
	UserID        pgtype.UUID
	BeverageID    pgtype.UUID
	UserLatitude  float64
	UserLongitude float64
}

func (q *Queries) CheckInBeverage(ctx context.Context, arg CheckInBeverageParams) (BeverageCheckin, error) {
	row := q.db.QueryRow(ctx, checkInBeverage,
		arg.UserID,
		arg.BeverageID,
		arg.UserLatitude,
		arg.UserLongitude,
	)
	var i BeverageCheckin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BeverageID,
		&i.CheckinDate,
		&i.UserLatitude,
		&i.UserLongitude,
		&i.CreatedAt,
	)
	return i, err
}

const getBeverageCheckInCounts = `-- name: GetBeverageCheckInCounts :one
SELECT
    COUNT(*)::bigint AS total_count,
    COUNT(DISTINCT user_id)::bigint AS unique_count
FROM beverage_checkins
WHERE beverage_id = $1
`

type GetBeverageCheckInCountsRow struct {
	TotalCount  int64
	UniqueCount int64
}

func (q *Queries) GetBeverageCheckInCounts(ctx context.Context, beverageID pgtype.UUID) (GetBeverageCheckInCountsRow, error) {
	row := q.db.QueryRow(ctx, getBeverageCheckInCounts, beverageID)
	var i GetBeverageCheckInCountsRow
	err := row.Scan(&i.TotalCount, &i.UniqueCount)
	return i, err
}

const hasUserCheckedInToday = `-- name: HasUserCheckedInToday :one
SELECT EXISTS(
    SELECT 1 FROM beverage_checkins
    WHERE user_id = $1 AND beverage_id = $2 AND checkin_date = CURRENT_DATE
) AS checked_in
`

type HasUserCheckedInTodayParams struct {
	UserID     pgtype.UUID
	BeverageID pgtype.UUID
}

func (q *Queries) HasUserCheckedInToday(ctx context.Context, arg HasUserCheckedInTodayParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserCheckedInToday, arg.UserID, arg.BeverageID)
	var checked_in bool
	err := row.Scan(&checked_in)
	return checked_in, err
}
