// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cron.sql

package store

import (
	"context"
)

const getLatestCronLog = `-- name: GetLatestCronLog :one
SELECT id, job_name, ran_at, items_affected, details FROM cron_log
WHERE job_name = $1
ORDER BY ran_at DESC
LIMIT 1
`

func (q *Queries) GetLatestCronLog(ctx context.Context, jobName string) (CronLog, error) {
	row := q.db.QueryRow(ctx, getLatestCronLog, jobName)
	var i CronLog
	err := row.Scan(
		&i.ID,
		&i.JobName,
		&i.RanAt,
		&i.ItemsAffected,
		&i.Details,
	)
	return i, err
}

const insertCronLog = `-- name: InsertCronLog :exec
INSERT INTO cron_log (job_name, items_affected, details)
VALUES ($1, $2, $3)
`

type InsertCronLogParams struct {
	JobName       string
	ItemsAffected int32
	Details       []byte
}

func (q *Queries) InsertCronLog(ctx context.Context, arg InsertCronLogParams) error {
	_, err := q.db.Exec(ctx, insertCronLog, arg.JobName, arg.ItemsAffected, arg.Details)
	return err
}
