// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: device_tokens.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec
DELETE FROM device_tokens WHERE token = $1 AND user_id = $2
`

type DeleteDeviceTokenParams struct {
	Token  string
	UserID pgtype.UUID
}

func (q *Queries) DeleteDeviceToken(ctx context.Context, arg DeleteDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, deleteDeviceToken, arg.Token, arg.UserID)
	return err
}

const deleteDeviceTokenByToken = `-- name: DeleteDeviceTokenByToken :exec
DELETE FROM device_tokens WHERE token = $1
`

func (q *Queries) DeleteDeviceTokenByToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteDeviceTokenByToken, token)
	return err
}

const listAllDeviceTokens = `-- name: ListAllDeviceTokens :many
SELECT dt.id, dt.token, dt.platform, u.id AS user_id, u.clerk_id
FROM device_tokens dt
JOIN users u ON u.id = dt.user_id
ORDER BY u.id, dt.created_at ASC
`

type ListAllDeviceTokensRow struct {
	ID       pgtype.UUID
	Token    string
	Platform string
	UserID   pgtype.UUID
	ClerkID  string
}

func (q *Queries) ListAllDeviceTokens(ctx context.Context) ([]ListAllDeviceTokensRow, error) {
	rows, err := q.db.Query(ctx, listAllDeviceTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllDeviceTokensRow
	for rows.Next() {
		var i ListAllDeviceTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.Platform,
			&i.UserID,
			&i.ClerkID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceTokensByUser = `-- name: ListDeviceTokensByUser :many
SELECT id, user_id, token, platform, created_at, updated_at FROM device_tokens WHERE user_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListDeviceTokensByUser(ctx context.Context, userID pgtype.UUID) ([]DeviceToken, error) {
	rows, err := q.db.Query(ctx, listDeviceTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceToken
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Platform,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :one
INSERT INTO device_tokens (user_id, token, platform)
VALUES ($1, $2, $3)
ON CONFLICT (token) DO UPDATE SET
    user_id = EXCLUDED.user_id,
    platform = EXCLUDED.platform,
    updated_at = NOW()
RETURNING id, user_id, token, platform, created_at, updated_at
`

type UpsertDeviceTokenParams struct {
	UserID   pgtype.UUID
	Token    string
	Platform string
}

func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (DeviceToken, error) {
	row := q.db.QueryRow(ctx, upsertDeviceToken, arg.UserID, arg.Token, arg.Platform)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Platform,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
