// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanOldDeletedExternalEvents = `-- name: CleanOldDeletedExternalEvents :execrows
DELETE FROM deleted_external_events
WHERE deleted_at < NOW() - INTERVAL '90 days'
`

func (q *Queries) CleanOldDeletedExternalEvents(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, cleanOldDeletedExternalEvents)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countEventsByLocation = `-- name: CountEventsByLocation :one
SELECT COUNT(*)
FROM events
WHERE ST_DWithin(
    ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography,
    ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography,
    $3::float
)
AND start_time >= $4::timestamptz
AND start_time < $5::timestamptz
AND ($6::text IS NULL OR $6::text = ANY(categories))
AND ($7::text IS NULL OR venue_name = $7::text)
AND ($8::uuid IS NULL OR venue_id = $8::uuid)
AND ($9::text IS NULL OR title ILIKE '%' || $9::text || '%' OR venue_name ILIKE '%' || $9::text || '%')
`

type CountEventsByLocationParams struct {
	Lng          float64
	Lat          float64
	RadiusMeters float64
	StartDate    pgtype.Timestamptz
	EndDate      pgtype.Timestamptz
	Category     pgtype.Text
	VenueName    pgtype.Text
	VenueID      pgtype.UUID
	Search       pgtype.Text
}

func (q *Queries) CountEventsByLocation(ctx context.Context, arg CountEventsByLocationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEventsByLocation,
		arg.Lng,
		arg.Lat,
		arg.RadiusMeters,
		arg.StartDate,
		arg.EndDate,
		arg.Category,
		arg.VenueName,
		arg.VenueID,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFeaturedThisMonth = `-- name: CountFeaturedThisMonth :one
SELECT COUNT(*) FROM events
WHERE featured_by = $1
  AND id <> $2
  AND featured_at >= date_trunc('month', now())
`

type CountFeaturedThisMonthParams struct {
	FeaturedBy pgtype.UUID
	ID         pgtype.UUID
}

// Distinct events the user has featured this calendar month, excluding a given
// event so re-featuring an already-counted event isn't double counted.
// featured_at/featured_by are retained across un-feature, so consumed slots
// aren't refunded.
func (q *Queries) CountFeaturedThisMonth(ctx context.Context, arg CountFeaturedThisMonthParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFeaturedThisMonth, arg.FeaturedBy, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMyFeaturedThisMonth = `-- name: CountMyFeaturedThisMonth :one
SELECT COUNT(*) FROM events
WHERE featured_by = $1
  AND featured_at >= date_trunc('month', now())
`

// Total distinct events the user has featured this calendar month (for the
// quota display); same counting basis as CountFeaturedThisMonth, no exclusion.
func (q *Queries) CountMyFeaturedThisMonth(ctx context.Context, featuredBy pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMyFeaturedThisMonth, featuredBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    source, title, description, venue_name, address, city, state, zip,
    latitude, longitude, start_time, end_time, categories, image_url,
    ticket_url, price_min, price_max, is_free, submitted_by, venue_id, series_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14,
    $15, $16, $17, $18, $19, $20, $21
) RETURNING id, external_id, source, title, description, venue_name, address, city, state, zip, latitude, longitude, start_time, end_time, image_url, ticket_url, price_min, price_max, submitted_by, created_at, updated_at, manually_edited, venue_id, categories, series_id, is_free, is_featured, featured_at, featured_by
`

type CreateEventParams struct {
	Source      string
	Title       string
	Description pgtype.Text
	VenueName   pgtype.Text
	Address     pgtype.Text
	City        pgtype.Text
	State       pgtype.Text
	Zip         pgtype.Text
	Latitude    float64
	Longitude   float64
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	Categories  []string
	ImageUrl    pgtype.Text
	TicketUrl   pgtype.Text
	PriceMin    pgtype.Numeric
	PriceMax    pgtype.Numeric
	IsFree      bool
	SubmittedBy pgtype.UUID
	VenueID     pgtype.UUID
	SeriesID    pgtype.UUID
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Source,
		arg.Title,
		arg.Description,
		arg.VenueName,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Latitude,
		arg.Longitude,
		arg.StartTime,
		arg.EndTime,
		arg.Categories,
		arg.ImageUrl,
		arg.TicketUrl,
		arg.PriceMin,
		arg.PriceMax,
		arg.IsFree,
		arg.SubmittedBy,
		arg.VenueID,
		arg.SeriesID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Source,
		&i.Title,
		&i.Description,
		&i.VenueName,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.StartTime,
		&i.EndTime,
		&i.ImageUrl,
		&i.TicketUrl,
		&i.PriceMin,
		&i.PriceMax,
		&i.SubmittedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ManuallyEdited,
		&i.VenueID,
		&i.Categories,
		&i.SeriesID,
		&i.IsFree,
		&i.IsFeatured,
		&i.FeaturedAt,
		&i.FeaturedBy,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const deletePastEvents = `-- name: DeletePastEvents :execrows
DELETE FROM events
WHERE start_time < NOW()::date
`

func (q *Queries) DeletePastEvents(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deletePastEvents)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const featureEvent = `-- name: FeatureEvent :one
UPDATE events SET is_featured = TRUE, featured_at = NOW(), featured_by = $2
WHERE id = $1
RETURNING id, external_id, source, title, description, venue_name, address, city, state, zip, latitude, longitude, start_time, end_time, image_url, ticket_url, price_min, price_max, submitted_by, created_at, updated_at, manually_edited, venue_id, categories, series_id, is_free, is_featured, featured_at, featured_by
`

type FeatureEventParams struct {
	ID         pgtype.UUID
	FeaturedBy pgtype.UUID
}

func (q *Queries) FeatureEvent(ctx context.Context, arg FeatureEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, featureEvent, arg.ID, arg.FeaturedBy)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Source,
		&i.Title,
		&i.Description,
		&i.VenueName,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.StartTime,
		&i.EndTime,
		&i.ImageUrl,
		&i.TicketUrl,
		&i.PriceMin,
		&i.PriceMax,
		&i.SubmittedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ManuallyEdited,
		&i.VenueID,
		&i.Categories,
		&i.SeriesID,
		&i.IsFree,
		&i.IsFeatured,
		&i.FeaturedAt,
		&i.FeaturedBy,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, external_id, source, title, description, venue_name, address, city, state, zip, latitude, longitude, start_time, end_time, image_url, ticket_url, price_min, price_max, submitted_by, created_at, updated_at, manually_edited, venue_id, categories, series_id, is_free, is_featured, featured_at, featured_by FROM events WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Source,
		&i.Title,
		&i.Description,
		&i.VenueName,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.StartTime,
		&i.EndTime,
		&i.ImageUrl,
		&i.TicketUrl,
		&i.PriceMin,
		&i.PriceMax,
		&i.SubmittedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ManuallyEdited,
		&i.VenueID,
		&i.Categories,
		&i.SeriesID,
		&i.IsFree,
		&i.IsFeatured,
		&i.FeaturedAt,
		&i.FeaturedBy,
	)
	return i, err
}

const getEventsByIDs = `-- name: GetEventsByIDs :many
SELECT id, external_id, source, title, description, venue_name, address, city, state, zip, latitude, longitude, start_time, end_time, image_url, ticket_url, price_min, price_max, submitted_by, created_at, updated_at, manually_edited, venue_id, categories, series_id, is_free, is_featured, featured_at, featured_by FROM events WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetEventsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Source,
			&i.Title,
			&i.Description,
			&i.VenueName,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Latitude,
			&i.Longitude,
			&i.StartTime,
			&i.EndTime,
			&i.ImageUrl,
			&i.TicketUrl,
			&i.PriceMin,
			&i.PriceMax,
			&i.SubmittedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ManuallyEdited,
			&i.VenueID,
			&i.Categories,
			&i.SeriesID,
			&i.IsFree,
			&i.IsFeatured,
			&i.FeaturedAt,
			&i.FeaturedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByLocation = `-- name: ListEventsByLocation :many
SELECT id, external_id, source, title, description, venue_name, address, city, state, zip, latitude, longitude, start_time, end_time, image_url, ticket_url, price_min, price_max, submitted_by, created_at, updated_at, manually_edited, venue_id, categories, series_id, is_free, is_featured, featured_at, featured_by
FROM events
WHERE ST_DWithin(
    ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography,
    ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography,
    $3::float
)
AND start_time >= $4::timestamptz
AND start_time < $5::timestamptz
AND ($6::text IS NULL OR $6::text = ANY(categories))
AND ($7::text IS NULL OR venue_name = $7::text)
AND ($8::uuid IS NULL OR venue_id = $8::uuid)
AND ($9::text IS NULL OR title ILIKE '%' || $9::text || '%' OR venue_name ILIKE '%' || $9::text || '%')
ORDER BY ST_Distance(
    ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography,
    ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography
) ASC, start_time ASC
LIMIT $11 OFFSET $10
`

type ListEventsByLocationParams struct {
	Lng          float64
	Lat          float64
	RadiusMeters float64
	StartDate    pgtype.Timestamptz
	EndDate      pgtype.Timestamptz
	Category     pgtype.Text
	VenueName    pgtype.Text
	VenueID      pgtype.UUID
	Search       pgtype.Text
	EventOffset  int32
	EventLimit   int32
}

func (q *Queries) ListEventsByLocation(ctx context.Context, arg ListEventsByLocationParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByLocation,
		arg.Lng,
		arg.Lat,
		arg.RadiusMeters,
		arg.StartDate,
		arg.EndDate,
		arg.Category,
		arg.VenueName,
		arg.VenueID,
		arg.Search,
		arg.EventOffset,
		arg.EventLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Source,
			&i.Title,
			&i.Description,
			&i.VenueName,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Latitude,
			&i.Longitude,
			&i.StartTime,
			&i.EndTime,
			&i.ImageUrl,
			&i.TicketUrl,
			&i.PriceMin,
			&i.PriceMax,
			&i.SubmittedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ManuallyEdited,
			&i.VenueID,
			&i.Categories,
			&i.SeriesID,
			&i.IsFree,
			&i.IsFeatured,
			&i.FeaturedAt,
			&i.FeaturedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByLocationDateSorted = `-- name: ListEventsByLocationDateSorted :many
SELECT id, external_id, source, title, description, venue_name, address, city, state, zip, latitude, longitude, start_time, end_time, image_url, ticket_url, price_min, price_max, submitted_by, created_at, updated_at, manually_edited, venue_id, categories, series_id, is_free, is_featured, featured_at, featured_by
FROM events
WHERE ST_DWithin(
    ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography,
    ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography,
    $3::float
)
AND start_time >= $4::timestamptz
AND start_time < $5::timestamptz
AND ($6::text IS NULL OR $6::text = ANY(categories))
AND ($7::text IS NULL OR venue_name = $7::text)
AND ($8::uuid IS NULL OR venue_id = $8::uuid)
AND ($9::text IS NULL OR title ILIKE '%' || $9::text || '%' OR venue_name ILIKE '%' || $9::text || '%')
ORDER BY (start_time AT TIME ZONE 'America/New_York')::date ASC,
    ST_Distance(
        ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography,
        ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography
    ) ASC,
    start_time ASC
LIMIT $11 OFFSET $10
`

type ListEventsByLocationDateSortedParams struct {
	Lng          float64
	Lat          float64
	RadiusMeters float64
	StartDate    pgtype.Timestamptz
	EndDate      pgtype.Timestamptz
	Category     pgtype.Text
	VenueName    pgtype.Text
	VenueID      pgtype.UUID
	Search       pgtype.Text
	EventOffset  int32
	EventLimit   int32
}

func (q *Queries) ListEventsByLocationDateSorted(ctx context.Context, arg ListEventsByLocationDateSortedParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByLocationDateSorted,
		arg.Lng,
		arg.Lat,
		arg.RadiusMeters,
		arg.StartDate,
		arg.EndDate,
		arg.Category,
		arg.VenueName,
		arg.VenueID,
		arg.Search,
		arg.EventOffset,
		arg.EventLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Source,
			&i.Title,
			&i.Description,
			&i.VenueName,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Latitude,
			&i.Longitude,
			&i.StartTime,
			&i.EndTime,
			&i.ImageUrl,
			&i.TicketUrl,
			&i.PriceMin,
			&i.PriceMax,
			&i.SubmittedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ManuallyEdited,
			&i.VenueID,
			&i.Categories,
			&i.SeriesID,
			&i.IsFree,
			&i.IsFeatured,
			&i.FeaturedAt,
			&i.FeaturedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsBySeries = `-- name: ListEventsBySeries :many
SELECT id, external_id, source, title, description, venue_name, address, city, state, zip, latitude, longitude, start_time, end_time, image_url, ticket_url, price_min, price_max, submitted_by, created_at, updated_at, manually_edited, venue_id, categories, series_id, is_free, is_featured, featured_at, featured_by FROM events
WHERE series_id = $1
ORDER BY start_time ASC
`

func (q *Queries) ListEventsBySeries(ctx context.Context, seriesID pgtype.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsBySeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Source,
			&i.Title,
			&i.Description,
			&i.VenueName,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Latitude,
			&i.Longitude,
			&i.StartTime,
			&i.EndTime,
			&i.ImageUrl,
			&i.TicketUrl,
			&i.PriceMin,
			&i.PriceMax,
			&i.SubmittedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ManuallyEdited,
			&i.VenueID,
			&i.Categories,
			&i.SeriesID,
			&i.IsFree,
			&i.IsFeatured,
			&i.FeaturedAt,
			&i.FeaturedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsBySubmitter = `-- name: ListEventsBySubmitter :many
SELECT id, external_id, source, title, description, venue_name, address, city, state, zip, latitude, longitude, start_time, end_time, image_url, ticket_url, price_min, price_max, submitted_by, created_at, updated_at, manually_edited, venue_id, categories, series_id, is_free, is_featured, featured_at, featured_by FROM events
WHERE submitted_by = $1
ORDER BY start_time ASC
`

func (q *Queries) ListEventsBySubmitter(ctx context.Context, submittedBy pgtype.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsBySubmitter, submittedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Source,
			&i.Title,
			&i.Description,
			&i.VenueName,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Latitude,
			&i.Longitude,
			&i.StartTime,
			&i.EndTime,
			&i.ImageUrl,
			&i.TicketUrl,
			&i.PriceMin,
			&i.PriceMax,
			&i.SubmittedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ManuallyEdited,
			&i.VenueID,
			&i.Categories,
			&i.SeriesID,
			&i.IsFree,
			&i.IsFeatured,
			&i.FeaturedAt,
			&i.FeaturedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeaturedEventsByLocation = `-- name: ListFeaturedEventsByLocation :many
SELECT id, external_id, source, title, description, venue_name, address, city, state, zip, latitude, longitude, start_time, end_time, image_url, ticket_url, price_min, price_max, submitted_by, created_at, updated_at, manually_edited, venue_id, categories, series_id, is_free, is_featured, featured_at, featured_by
FROM events
WHERE is_featured = TRUE
AND start_time >= NOW()
AND ST_DWithin(
    ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography,
    ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography,
    $3::float
)
ORDER BY start_time ASC,
    ST_Distance(
        ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography,
        ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography
    ) ASC
LIMIT $4
`

type ListFeaturedEventsByLocationParams struct {
	Lng          float64
	Lat          float64
	RadiusMeters float64
	EventLimit   int32
}

// Upcoming featured events near a location, soonest first.
func (q *Queries) ListFeaturedEventsByLocation(ctx context.Context, arg ListFeaturedEventsByLocationParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listFeaturedEventsByLocation,
		arg.Lng,
		arg.Lat,
		arg.RadiusMeters,
		arg.EventLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Source,
			&i.Title,
			&i.Description,
			&i.VenueName,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Latitude,
			&i.Longitude,
			&i.StartTime,
			&i.EndTime,
			&i.ImageUrl,
			&i.TicketUrl,
			&i.PriceMin,
			&i.PriceMax,
			&i.SubmittedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ManuallyEdited,
			&i.VenueID,
			&i.Categories,
			&i.SeriesID,
			&i.IsFree,
			&i.IsFeatured,
			&i.FeaturedAt,
			&i.FeaturedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyFeaturedEvents = `-- name: ListMyFeaturedEvents :many
SELECT id, external_id, source, title, description, venue_name, address, city, state, zip, latitude, longitude, start_time, end_time, image_url, ticket_url, price_min, price_max, submitted_by, created_at, updated_at, manually_edited, venue_id, categories, series_id, is_free, is_featured, featured_at, featured_by FROM events
WHERE featured_by = $1 AND is_featured = TRUE
ORDER BY start_time ASC
`

// Events the user currently has featured, soonest first.
func (q *Queries) ListMyFeaturedEvents(ctx context.Context, featuredBy pgtype.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, listMyFeaturedEvents, featuredBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Source,
			&i.Title,
			&i.Description,
			&i.VenueName,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Latitude,
			&i.Longitude,
			&i.StartTime,
			&i.EndTime,
			&i.ImageUrl,
			&i.TicketUrl,
			&i.PriceMin,
			&i.PriceMax,
			&i.SubmittedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ManuallyEdited,
			&i.VenueID,
			&i.Categories,
			&i.SeriesID,
			&i.IsFree,
			&i.IsFeatured,
			&i.FeaturedAt,
			&i.FeaturedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPastEventImageURLs = `-- name: ListPastEventImageURLs :many
SELECT DISTINCT image_url
FROM events
WHERE start_time < NOW()::date
  AND image_url IS NOT NULL
  AND image_url LIKE '%/events/%'
  AND image_url NOT IN (
      SELECT image_url FROM events
      WHERE start_time >= NOW()::date
        AND image_url IS NOT NULL
  )
`

func (q *Queries) ListPastEventImageURLs(ctx context.Context) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listPastEventImageURLs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var image_url pgtype.Text
		if err := rows.Scan(&image_url); err != nil {
			return nil, err
		}
		items = append(items, image_url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trackDeletedExternalEvent = `-- name: TrackDeletedExternalEvent :exec
INSERT INTO deleted_external_events (source, external_id)
VALUES ($1, $2)
ON CONFLICT (source, external_id) DO NOTHING
`

type TrackDeletedExternalEventParams struct {
	Source     string
	ExternalID string
}

func (q *Queries) TrackDeletedExternalEvent(ctx context.Context, arg TrackDeletedExternalEventParams) error {
	_, err := q.db.Exec(ctx, trackDeletedExternalEvent, arg.Source, arg.ExternalID)
	return err
}

const unfeatureEvent = `-- name: UnfeatureEvent :one
UPDATE events SET is_featured = FALSE
WHERE id = $1
RETURNING id, external_id, source, title, description, venue_name, address, city, state, zip, latitude, longitude, start_time, end_time, image_url, ticket_url, price_min, price_max, submitted_by, created_at, updated_at, manually_edited, venue_id, categories, series_id, is_free, is_featured, featured_at, featured_by
`

// Keeps featured_at / featured_by as an audit trail.
func (q *Queries) UnfeatureEvent(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, unfeatureEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Source,
		&i.Title,
		&i.Description,
		&i.VenueName,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.StartTime,
		&i.EndTime,
		&i.ImageUrl,
		&i.TicketUrl,
		&i.PriceMin,
		&i.PriceMax,
		&i.SubmittedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ManuallyEdited,
		&i.VenueID,
		&i.Categories,
		&i.SeriesID,
		&i.IsFree,
		&i.IsFeatured,
		&i.FeaturedAt,
		&i.FeaturedBy,
	)
	return i, err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events SET
    title = $2,
    description = $3,
    venue_name = $4,
    address = $5,
    city = $6,
    state = $7,
    zip = $8,
    latitude = $9,
    longitude = $10,
    start_time = $11,
    end_time = $12,
    categories = $13,
    image_url = $14,
    ticket_url = $15,
    price_min = $16,
    price_max = $17,
    is_free = $18,
    venue_id = $19,
    manually_edited = TRUE,
    updated_at = NOW()
WHERE id = $1
RETURNING id, external_id, source, title, description, venue_name, address, city, state, zip, latitude, longitude, start_time, end_time, image_url, ticket_url, price_min, price_max, submitted_by, created_at, updated_at, manually_edited, venue_id, categories, series_id, is_free, is_featured, featured_at, featured_by
`

type UpdateEventParams struct {
	ID          pgtype.UUID
	Title       string
	Description pgtype.Text
	VenueName   pgtype.Text
	Address     pgtype.Text
	City        pgtype.Text
	State       pgtype.Text
	Zip         pgtype.Text
	Latitude    float64
	Longitude   float64
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	Categories  []string
	ImageUrl    pgtype.Text
	TicketUrl   pgtype.Text
	PriceMin    pgtype.Numeric
	PriceMax    pgtype.Numeric
	IsFree      bool
	VenueID     pgtype.UUID
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.VenueName,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Latitude,
		arg.Longitude,
		arg.StartTime,
		arg.EndTime,
		arg.Categories,
		arg.ImageUrl,
		arg.TicketUrl,
		arg.PriceMin,
		arg.PriceMax,
		arg.IsFree,
		arg.VenueID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Source,
		&i.Title,
		&i.Description,
		&i.VenueName,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.StartTime,
		&i.EndTime,
		&i.ImageUrl,
		&i.TicketUrl,
		&i.PriceMin,
		&i.PriceMax,
		&i.SubmittedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ManuallyEdited,
		&i.VenueID,
		&i.Categories,
		&i.SeriesID,
		&i.IsFree,
		&i.IsFeatured,
		&i.FeaturedAt,
		&i.FeaturedBy,
	)
	return i, err
}

const updateEventsBySeries = `-- name: UpdateEventsBySeries :many
UPDATE events SET
    title = $2,
    description = $3,
    venue_name = $4,
    address = $5,
    city = $6,
    state = $7,
    zip = $8,
    latitude = $9,
    longitude = $10,
    categories = $11,
    image_url = $12,
    ticket_url = $13,
    price_min = $14,
    price_max = $15,
    is_free = $16,
    venue_id = $17,
    manually_edited = TRUE,
    updated_at = NOW()
WHERE series_id = $1
RETURNING id, external_id, source, title, description, venue_name, address, city, state, zip, latitude, longitude, start_time, end_time, image_url, ticket_url, price_min, price_max, submitted_by, created_at, updated_at, manually_edited, venue_id, categories, series_id, is_free, is_featured, featured_at, featured_by
`

type UpdateEventsBySeriesParams struct {
	SeriesID    pgtype.UUID
	Title       string
	Description pgtype.Text
	VenueName   pgtype.Text
	Address     pgtype.Text
	City        pgtype.Text
	State       pgtype.Text
	Zip         pgtype.Text
	Latitude    float64
	Longitude   float64
	Categories  []string
	ImageUrl    pgtype.Text
	TicketUrl   pgtype.Text
	PriceMin    pgtype.Numeric
	PriceMax    pgtype.Numeric
	IsFree      bool
	VenueID     pgtype.UUID
}

func (q *Queries) UpdateEventsBySeries(ctx context.Context, arg UpdateEventsBySeriesParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, updateEventsBySeries,
		arg.SeriesID,
		arg.Title,
		arg.Description,
		arg.VenueName,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Latitude,
		arg.Longitude,
		arg.Categories,
		arg.ImageUrl,
		arg.TicketUrl,
		arg.PriceMin,
		arg.PriceMax,
		arg.IsFree,
		arg.VenueID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Source,
			&i.Title,
			&i.Description,
			&i.VenueName,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Latitude,
			&i.Longitude,
			&i.StartTime,
			&i.EndTime,
			&i.ImageUrl,
			&i.TicketUrl,
			&i.PriceMin,
			&i.PriceMax,
			&i.SubmittedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ManuallyEdited,
			&i.VenueID,
			&i.Categories,
			&i.SeriesID,
			&i.IsFree,
			&i.IsFeatured,
			&i.FeaturedAt,
			&i.FeaturedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExternalEvent = `-- name: UpsertExternalEvent :one
INSERT INTO events (
    external_id, source, title, description, venue_name, address, city, state, zip,
    latitude, longitude, start_time, end_time, categories, image_url,
    ticket_url, price_min, price_max, is_free, venue_id
) SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20
WHERE NOT EXISTS (
    SELECT 1 FROM deleted_external_events d
    WHERE d.source = $2 AND d.external_id = $1
)
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL
DO UPDATE SET
    title=EXCLUDED.title, description=EXCLUDED.description,
    venue_name=EXCLUDED.venue_name, address=EXCLUDED.address,
    city=EXCLUDED.city, state=EXCLUDED.state, zip=EXCLUDED.zip,
    latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude,
    start_time=EXCLUDED.start_time, end_time=EXCLUDED.end_time,
    categories=EXCLUDED.categories, image_url=EXCLUDED.image_url,
    ticket_url=EXCLUDED.ticket_url, price_min=EXCLUDED.price_min,
    price_max=EXCLUDED.price_max, is_free=EXCLUDED.is_free,
    venue_id=EXCLUDED.venue_id, updated_at=NOW()
WHERE NOT events.manually_edited
RETURNING id, external_id, source, title, description, venue_name, address, city, state, zip, latitude, longitude, start_time, end_time, image_url, ticket_url, price_min, price_max, submitted_by, created_at, updated_at, manually_edited, venue_id, categories, series_id, is_free, is_featured, featured_at, featured_by
`

type UpsertExternalEventParams struct {
	ExternalID  pgtype.Text
	Source      string
	Title       string
	Description pgtype.Text
	VenueName   pgtype.Text
	Address     pgtype.Text
	City        pgtype.Text
	State       pgtype.Text
	Zip         pgtype.Text
	Latitude    float64
	Longitude   float64
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	Categories  []string
	ImageUrl    pgtype.Text
	TicketUrl   pgtype.Text
	PriceMin    pgtype.Numeric
	PriceMax    pgtype.Numeric
	IsFree      bool
	VenueID     pgtype.UUID
}

func (q *Queries) UpsertExternalEvent(ctx context.Context, arg UpsertExternalEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, upsertExternalEvent,
		arg.ExternalID,
		arg.Source,
		arg.Title,
		arg.Description,
		arg.VenueName,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Latitude,
		arg.Longitude,
		arg.StartTime,
		arg.EndTime,
		arg.Categories,
		arg.ImageUrl,
		arg.TicketUrl,
		arg.PriceMin,
		arg.PriceMax,
		arg.IsFree,
		arg.VenueID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Source,
		&i.Title,
		&i.Description,
		&i.VenueName,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.StartTime,
		&i.EndTime,
		&i.ImageUrl,
		&i.TicketUrl,
		&i.PriceMin,
		&i.PriceMax,
		&i.SubmittedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ManuallyEdited,
		&i.VenueID,
		&i.Categories,
		&i.SeriesID,
		&i.IsFree,
		&i.IsFeatured,
		&i.FeaturedAt,
		&i.FeaturedBy,
	)
	return i, err
}
