// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: food_checkins.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkInFood = `-- name: CheckInFood :one
INSERT INTO food_checkins (user_id, food_id, user_latitude, user_longitude)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, food_id, checkin_date) DO NOTHING
RETURNING id, user_id, food_id, checkin_date, user_latitude, user_longitude, created_at
`

type CheckInFoodParams struct {
	UserID        pgtype.UUID
	FoodID        pgtype.UUID
	UserLatitude  float64
	UserLongitude float64
}

func (q *Queries) CheckInFood(ctx context.Context, arg CheckInFoodParams) (FoodCheckin, error) {
	row := q.db.QueryRow(ctx, checkInFood,
		arg.UserID,
		arg.FoodID,
		arg.UserLatitude,
		arg.UserLongitude,
	)
	var i FoodCheckin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FoodID,
		&i.CheckinDate,
		&i.UserLatitude,
		&i.UserLongitude,
		&i.CreatedAt,
	)
	return i, err
}

const getFoodCheckInCounts = `-- name: GetFoodCheckInCounts :one
SELECT
    COUNT(*)::bigint AS total_count,
    COUNT(DISTINCT user_id)::bigint AS unique_count
FROM food_checkins
WHERE food_id = $1
`

type GetFoodCheckInCountsRow struct {
	TotalCount  int64
	UniqueCount int64
}

func (q *Queries) GetFoodCheckInCounts(ctx context.Context, foodID pgtype.UUID) (GetFoodCheckInCountsRow, error) {
	row := q.db.QueryRow(ctx, getFoodCheckInCounts, foodID)
	var i GetFoodCheckInCountsRow
	err := row.Scan(&i.TotalCount, &i.UniqueCount)
	return i, err
}

const getUserFoodCheckInStats = `-- name: GetUserFoodCheckInStats :one
SELECT
    COUNT(*)::bigint AS total_checkins,
    COUNT(DISTINCT food_id)::bigint AS unique_restaurants,
    MIN(c.checkin_date)::date AS first_checkin_date,
    MAX(c.checkin_date)::date AS last_checkin_date
FROM food_checkins c
WHERE c.user_id = $1
`

type GetUserFoodCheckInStatsRow struct {
	TotalCheckins     int64
	UniqueRestaurants int64
	FirstCheckinDate  pgtype.Date
	LastCheckinDate   pgtype.Date
}

func (q *Queries) GetUserFoodCheckInStats(ctx context.Context, userID pgtype.UUID) (GetUserFoodCheckInStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserFoodCheckInStats, userID)
	var i GetUserFoodCheckInStatsRow
	err := row.Scan(
		&i.TotalCheckins,
		&i.UniqueRestaurants,
		&i.FirstCheckinDate,
		&i.LastCheckinDate,
	)
	return i, err
}

const hasUserCheckedInFoodToday = `-- name: HasUserCheckedInFoodToday :one
SELECT EXISTS(
    SELECT 1 FROM food_checkins
    WHERE user_id = $1 AND food_id = $2 AND checkin_date = CURRENT_DATE
) AS checked_in
`

type HasUserCheckedInFoodTodayParams struct {
	UserID pgtype.UUID
	FoodID pgtype.UUID
}

func (q *Queries) HasUserCheckedInFoodToday(ctx context.Context, arg HasUserCheckedInFoodTodayParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserCheckedInFoodToday, arg.UserID, arg.FoodID)
	var checked_in bool
	err := row.Scan(&checked_in)
	return checked_in, err
}

const listUserFoodCheckIns = `-- name: ListUserFoodCheckIns :many
SELECT
    c.id,
    c.food_id,
    c.checkin_date,
    c.created_at,
    f.name AS food_name,
    f.cuisine AS food_cuisine,
    f.city AS food_city,
    f.image_url AS food_image_url
FROM food_checkins c
JOIN foods f ON f.id = c.food_id
WHERE c.user_id = $1
ORDER BY c.checkin_date DESC, c.created_at DESC
`

type ListUserFoodCheckInsRow struct {
	ID           pgtype.UUID
	FoodID       pgtype.UUID
	CheckinDate  pgtype.Date
	CreatedAt    pgtype.Timestamptz
	FoodName     string
	FoodCuisine  string
	FoodCity     pgtype.Text
	FoodImageUrl pgtype.Text
}

func (q *Queries) ListUserFoodCheckIns(ctx context.Context, userID pgtype.UUID) ([]ListUserFoodCheckInsRow, error) {
	rows, err := q.db.Query(ctx, listUserFoodCheckIns, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserFoodCheckInsRow
	for rows.Next() {
		var i ListUserFoodCheckInsRow
		if err := rows.Scan(
			&i.ID,
			&i.FoodID,
			&i.CheckinDate,
			&i.CreatedAt,
			&i.FoodName,
			&i.FoodCuisine,
			&i.FoodCity,
			&i.FoodImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
