// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: foods.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFood = `-- name: CreateFood :one
INSERT INTO foods (name, cuisine, address, city, state, zip, latitude, longitude, phone, website, hours, description, review, image_url, tags, price_level)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, name, cuisine, address, city, state, zip, latitude, longitude, phone, website, hours, description, review, image_url, tags, price_level, created_at, updated_at
`

type CreateFoodParams struct {
	Name        string
	Cuisine     string
	Address     pgtype.Text
	City        pgtype.Text
	State       pgtype.Text
	Zip         pgtype.Text
	Latitude    float64
	Longitude   float64
	Phone       pgtype.Text
	Website     pgtype.Text
	Hours       pgtype.Text
	Description pgtype.Text
	Review      pgtype.Text
	ImageUrl    pgtype.Text
	Tags        []string
	PriceLevel  pgtype.Int4
}

func (q *Queries) CreateFood(ctx context.Context, arg CreateFoodParams) (Food, error) {
	row := q.db.QueryRow(ctx, createFood,
		arg.Name,
		arg.Cuisine,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Latitude,
		arg.Longitude,
		arg.Phone,
		arg.Website,
		arg.Hours,
		arg.Description,
		arg.Review,
		arg.ImageUrl,
		arg.Tags,
		arg.PriceLevel,
	)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cuisine,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.Phone,
		&i.Website,
		&i.Hours,
		&i.Description,
		&i.Review,
		&i.ImageUrl,
		&i.Tags,
		&i.PriceLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFood = `-- name: DeleteFood :exec
DELETE FROM foods WHERE id = $1
`

func (q *Queries) DeleteFood(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFood, id)
	return err
}

const getFood = `-- name: GetFood :one
SELECT id, name, cuisine, address, city, state, zip, latitude, longitude, phone, website, hours, description, review, image_url, tags, price_level, created_at, updated_at FROM foods WHERE id = $1
`

func (q *Queries) GetFood(ctx context.Context, id pgtype.UUID) (Food, error) {
	row := q.db.QueryRow(ctx, getFood, id)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cuisine,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.Phone,
		&i.Website,
		&i.Hours,
		&i.Description,
		&i.Review,
		&i.ImageUrl,
		&i.Tags,
		&i.PriceLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFoodsByLocation = `-- name: ListFoodsByLocation :many
SELECT id, name, cuisine, address, city, state, zip, latitude, longitude, phone, website, hours, description, review, image_url, tags, price_level, created_at, updated_at
FROM foods
WHERE ST_DWithin(
    ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography,
    ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography,
    $3::float
)
AND (cardinality($4::text[]) = 0 OR cuisine = ANY($4::text[]))
AND ($5::int IS NULL OR price_level >= $5::int)
AND ($6::int IS NULL OR price_level <= $6::int)
AND ($7::text IS NULL
     OR name ILIKE '%' || $7::text || '%'
     OR description ILIKE '%' || $7::text || '%'
     OR city ILIKE '%' || $7::text || '%')
ORDER BY ST_Distance(
    ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography,
    ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography
) ASC
`

type ListFoodsByLocationParams struct {
	Lng          float64
	Lat          float64
	RadiusMeters float64
	Cuisines     []string
	MinPrice     pgtype.Int4
	MaxPrice     pgtype.Int4
	Search       pgtype.Text
}

func (q *Queries) ListFoodsByLocation(ctx context.Context, arg ListFoodsByLocationParams) ([]Food, error) {
	rows, err := q.db.Query(ctx, listFoodsByLocation,
		arg.Lng,
		arg.Lat,
		arg.RadiusMeters,
		arg.Cuisines,
		arg.MinPrice,
		arg.MaxPrice,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Food
	for rows.Next() {
		var i Food
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Cuisine,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Latitude,
			&i.Longitude,
			&i.Phone,
			&i.Website,
			&i.Hours,
			&i.Description,
			&i.Review,
			&i.ImageUrl,
			&i.Tags,
			&i.PriceLevel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFood = `-- name: UpdateFood :one
UPDATE foods SET
    name = $2,
    cuisine = $3,
    address = $4,
    city = $5,
    state = $6,
    zip = $7,
    latitude = $8,
    longitude = $9,
    phone = $10,
    website = $11,
    hours = $12,
    description = $13,
    review = $14,
    image_url = $15,
    tags = $16,
    price_level = $17,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, cuisine, address, city, state, zip, latitude, longitude, phone, website, hours, description, review, image_url, tags, price_level, created_at, updated_at
`

type UpdateFoodParams struct {
	ID          pgtype.UUID
	Name        string
	Cuisine     string
	Address     pgtype.Text
	City        pgtype.Text
	State       pgtype.Text
	Zip         pgtype.Text
	Latitude    float64
	Longitude   float64
	Phone       pgtype.Text
	Website     pgtype.Text
	Hours       pgtype.Text
	Description pgtype.Text
	Review      pgtype.Text
	ImageUrl    pgtype.Text
	Tags        []string
	PriceLevel  pgtype.Int4
}

func (q *Queries) UpdateFood(ctx context.Context, arg UpdateFoodParams) (Food, error) {
	row := q.db.QueryRow(ctx, updateFood,
		arg.ID,
		arg.Name,
		arg.Cuisine,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Latitude,
		arg.Longitude,
		arg.Phone,
		arg.Website,
		arg.Hours,
		arg.Description,
		arg.Review,
		arg.ImageUrl,
		arg.Tags,
		arg.PriceLevel,
	)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cuisine,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.Phone,
		&i.Website,
		&i.Hours,
		&i.Description,
		&i.Review,
		&i.ImageUrl,
		&i.Tags,
		&i.PriceLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
