// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthorApplication struct {
	ID          pgtype.UUID
	ClerkID     string
	FullName    string
	Email       string
	Bio         string
	Experience  string
	Status      string
	SubmittedAt pgtype.Timestamptz
	ReviewedAt  pgtype.Timestamptz
	ReviewedBy  pgtype.Text
	ReviewNotes pgtype.Text
}

type Beverage struct {
	ID          pgtype.UUID
	Name        string
	Type        string
	Address     pgtype.Text
	City        pgtype.Text
	State       pgtype.Text
	Zip         pgtype.Text
	Latitude    float64
	Longitude   float64
	Phone       pgtype.Text
	Website     pgtype.Text
	Hours       pgtype.Text
	Description pgtype.Text
	Review      pgtype.Text
	ImageUrl    pgtype.Text
	Tags        []string
	PriceLevel  pgtype.Int4
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type BeverageCheckin struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	BeverageID    pgtype.UUID
	CheckinDate   pgtype.Date
	UserLatitude  float64
	UserLongitude float64
	CreatedAt     pgtype.Timestamptz
}

type CronLog struct {
	ID            pgtype.UUID
	JobName       string
	RanAt         pgtype.Timestamptz
	ItemsAffected int32
	Details       []byte
}

type DeletedExternalEvent struct {
	Source     string
	ExternalID string
	DeletedAt  pgtype.Timestamptz
}

type EditSuggestion struct {
	ID              pgtype.UUID
	TargetType      string
	TargetID        pgtype.UUID
	SubmittedBy     pgtype.UUID
	ProposedChanges []byte
	Status          string
	ReviewNotes     pgtype.Text
	ReviewedBy      pgtype.Text
	CreatedAt       pgtype.Timestamptz
	ReviewedAt      pgtype.Timestamptz
	Action          string
	Reason          pgtype.Text
}

type Event struct {
	ID             pgtype.UUID
	ExternalID     pgtype.Text
	Source         string
	Title          string
	Description    pgtype.Text
	VenueName      pgtype.Text
	Address        pgtype.Text
	City           pgtype.Text
	State          pgtype.Text
	Zip            pgtype.Text
	Latitude       float64
	Longitude      float64
	StartTime      pgtype.Timestamptz
	EndTime        pgtype.Timestamptz
	ImageUrl       pgtype.Text
	TicketUrl      pgtype.Text
	PriceMin       pgtype.Numeric
	PriceMax       pgtype.Numeric
	SubmittedBy    pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ManuallyEdited bool
	VenueID        pgtype.UUID
	Categories     []string
	SeriesID       pgtype.UUID
}

type Image struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	R2Key       string
	Url         string
	Filename    string
	ContentType string
	SizeBytes   pgtype.Int8
	CreatedAt   pgtype.Timestamptz
}

type NotificationLog struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Channel      string
	SentAt       pgtype.Timestamptz
	EventCount   int32
	Status       string
	ErrorMessage pgtype.Text
}

type NotificationPreference struct {
	ID                    pgtype.UUID
	UserID                pgtype.UUID
	EmailEnabled          bool
	SmsEnabled            bool
	EmailUnsubscribeToken pgtype.UUID
	SmsUnsubscribeToken   pgtype.UUID
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	PreferredCategories   []string
	DigestFormat          string
	EmailStyle            string
}

type SavedEvent struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	EventID   pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID                 pgtype.UUID
	ClerkID            string
	Username           pgtype.Text
	Email              pgtype.Text
	DefaultLatitude    pgtype.Float8
	DefaultLongitude   pgtype.Float8
	DefaultRadiusMiles pgtype.Int4
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	PhoneNumber        pgtype.Text
}

type Venue struct {
	ID          pgtype.UUID
	Name        string
	Address     pgtype.Text
	City        pgtype.Text
	State       pgtype.Text
	Zip         pgtype.Text
	Latitude    float64
	Longitude   float64
	Hours       pgtype.Text
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
