// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotificationLog = `-- name: CreateNotificationLog :exec
INSERT INTO notification_log (user_id, channel, event_count, status, error_message)
VALUES ($1, $2, $3, $4, $5)
`

type CreateNotificationLogParams struct {
	UserID       pgtype.UUID
	Channel      string
	EventCount   int32
	Status       string
	ErrorMessage pgtype.Text
}

func (q *Queries) CreateNotificationLog(ctx context.Context, arg CreateNotificationLogParams) error {
	_, err := q.db.Exec(ctx, createNotificationLog,
		arg.UserID,
		arg.Channel,
		arg.EventCount,
		arg.Status,
		arg.ErrorMessage,
	)
	return err
}

const getEmailSubscriberByID = `-- name: GetEmailSubscriberByID :one
SELECT u.id, u.email, u.default_latitude, u.default_longitude, u.default_radius_miles,
       np.email_unsubscribe_token, np.preferred_categories, np.digest_format, np.email_style
FROM users u
JOIN notification_preferences np ON np.user_id = u.id
WHERE u.id = $1
  AND np.email_enabled = TRUE
  AND u.email IS NOT NULL
  AND u.default_latitude IS NOT NULL
  AND u.default_longitude IS NOT NULL
`

type GetEmailSubscriberByIDRow struct {
	ID                    pgtype.UUID
	Email                 pgtype.Text
	DefaultLatitude       pgtype.Float8
	DefaultLongitude      pgtype.Float8
	DefaultRadiusMiles    pgtype.Int4
	EmailUnsubscribeToken pgtype.UUID
	PreferredCategories   []string
	DigestFormat          string
	EmailStyle            string
}

func (q *Queries) GetEmailSubscriberByID(ctx context.Context, id pgtype.UUID) (GetEmailSubscriberByIDRow, error) {
	row := q.db.QueryRow(ctx, getEmailSubscriberByID, id)
	var i GetEmailSubscriberByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DefaultLatitude,
		&i.DefaultLongitude,
		&i.DefaultRadiusMiles,
		&i.EmailUnsubscribeToken,
		&i.PreferredCategories,
		&i.DigestFormat,
		&i.EmailStyle,
	)
	return i, err
}

const getLastNotificationSent = `-- name: GetLastNotificationSent :one
SELECT id, user_id, channel, sent_at, event_count, status, error_message FROM notification_log
WHERE user_id = $1 AND channel = $2 AND status = 'sent'
ORDER BY sent_at DESC
LIMIT 1
`

type GetLastNotificationSentParams struct {
	UserID  pgtype.UUID
	Channel string
}

func (q *Queries) GetLastNotificationSent(ctx context.Context, arg GetLastNotificationSentParams) (NotificationLog, error) {
	row := q.db.QueryRow(ctx, getLastNotificationSent, arg.UserID, arg.Channel)
	var i NotificationLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Channel,
		&i.SentAt,
		&i.EventCount,
		&i.Status,
		&i.ErrorMessage,
	)
	return i, err
}

const getNotificationPreferences = `-- name: GetNotificationPreferences :one
SELECT id, user_id, email_enabled, sms_enabled, email_unsubscribe_token, sms_unsubscribe_token, created_at, updated_at, preferred_categories, digest_format, email_style FROM notification_preferences WHERE user_id = $1
`

func (q *Queries) GetNotificationPreferences(ctx context.Context, userID pgtype.UUID) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, getNotificationPreferences, userID)
	var i NotificationPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EmailEnabled,
		&i.SmsEnabled,
		&i.EmailUnsubscribeToken,
		&i.SmsUnsubscribeToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PreferredCategories,
		&i.DigestFormat,
		&i.EmailStyle,
	)
	return i, err
}

const listEmailSubscribers = `-- name: ListEmailSubscribers :many
SELECT u.id, u.email, u.default_latitude, u.default_longitude, u.default_radius_miles,
       np.email_unsubscribe_token, np.preferred_categories, np.digest_format, np.email_style
FROM users u
JOIN notification_preferences np ON np.user_id = u.id
WHERE np.email_enabled = TRUE
  AND u.email IS NOT NULL
  AND u.default_latitude IS NOT NULL
  AND u.default_longitude IS NOT NULL
`

type ListEmailSubscribersRow struct {
	ID                    pgtype.UUID
	Email                 pgtype.Text
	DefaultLatitude       pgtype.Float8
	DefaultLongitude      pgtype.Float8
	DefaultRadiusMiles    pgtype.Int4
	EmailUnsubscribeToken pgtype.UUID
	PreferredCategories   []string
	DigestFormat          string
	EmailStyle            string
}

func (q *Queries) ListEmailSubscribers(ctx context.Context) ([]ListEmailSubscribersRow, error) {
	rows, err := q.db.Query(ctx, listEmailSubscribers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmailSubscribersRow
	for rows.Next() {
		var i ListEmailSubscribersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DefaultLatitude,
			&i.DefaultLongitude,
			&i.DefaultRadiusMiles,
			&i.EmailUnsubscribeToken,
			&i.PreferredCategories,
			&i.DigestFormat,
			&i.EmailStyle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSMSSubscribers = `-- name: ListSMSSubscribers :many
SELECT u.id, u.clerk_id, u.phone_number, u.default_latitude, u.default_longitude, u.default_radius_miles,
       np.sms_unsubscribe_token, np.preferred_categories
FROM users u
JOIN notification_preferences np ON np.user_id = u.id
WHERE np.sms_enabled = TRUE
  AND u.phone_number IS NOT NULL
  AND u.default_latitude IS NOT NULL
  AND u.default_longitude IS NOT NULL
`

type ListSMSSubscribersRow struct {
	ID                  pgtype.UUID
	ClerkID             string
	PhoneNumber         pgtype.Text
	DefaultLatitude     pgtype.Float8
	DefaultLongitude    pgtype.Float8
	DefaultRadiusMiles  pgtype.Int4
	SmsUnsubscribeToken pgtype.UUID
	PreferredCategories []string
}

func (q *Queries) ListSMSSubscribers(ctx context.Context) ([]ListSMSSubscribersRow, error) {
	rows, err := q.db.Query(ctx, listSMSSubscribers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSMSSubscribersRow
	for rows.Next() {
		var i ListSMSSubscribersRow
		if err := rows.Scan(
			&i.ID,
			&i.ClerkID,
			&i.PhoneNumber,
			&i.DefaultLatitude,
			&i.DefaultLongitude,
			&i.DefaultRadiusMiles,
			&i.SmsUnsubscribeToken,
			&i.PreferredCategories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingEventsForDigest = `-- name: ListUpcomingEventsForDigest :many
SELECT id, external_id, source, title, description, venue_name, address, city, state, zip, latitude, longitude, start_time, end_time, image_url, ticket_url, price_min, price_max, submitted_by, created_at, updated_at, manually_edited, venue_id, categories, series_id
FROM events
WHERE ST_DWithin(
    ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography,
    ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography,
    $3::float
)
AND start_time >= $4::timestamptz
AND start_time < $5::timestamptz
ORDER BY start_time ASC
LIMIT $6::int
`

type ListUpcomingEventsForDigestParams struct {
	Lng          float64
	Lat          float64
	RadiusMeters float64
	StartDate    pgtype.Timestamptz
	EndDate      pgtype.Timestamptz
	MaxEvents    int32
}

func (q *Queries) ListUpcomingEventsForDigest(ctx context.Context, arg ListUpcomingEventsForDigestParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listUpcomingEventsForDigest,
		arg.Lng,
		arg.Lat,
		arg.RadiusMeters,
		arg.StartDate,
		arg.EndDate,
		arg.MaxEvents,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Source,
			&i.Title,
			&i.Description,
			&i.VenueName,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Latitude,
			&i.Longitude,
			&i.StartTime,
			&i.EndTime,
			&i.ImageUrl,
			&i.TicketUrl,
			&i.PriceMin,
			&i.PriceMax,
			&i.SubmittedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ManuallyEdited,
			&i.VenueID,
			&i.Categories,
			&i.SeriesID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resubscribeSMSByPhoneNumber = `-- name: ResubscribeSMSByPhoneNumber :exec
UPDATE notification_preferences SET sms_enabled = TRUE, updated_at = NOW()
WHERE user_id = (SELECT id FROM users WHERE phone_number = $1 LIMIT 1)
`

func (q *Queries) ResubscribeSMSByPhoneNumber(ctx context.Context, phoneNumber pgtype.Text) error {
	_, err := q.db.Exec(ctx, resubscribeSMSByPhoneNumber, phoneNumber)
	return err
}

const unsubscribeByEmailToken = `-- name: UnsubscribeByEmailToken :exec
UPDATE notification_preferences SET email_enabled = FALSE, updated_at = NOW()
WHERE email_unsubscribe_token = $1
`

func (q *Queries) UnsubscribeByEmailToken(ctx context.Context, emailUnsubscribeToken pgtype.UUID) error {
	_, err := q.db.Exec(ctx, unsubscribeByEmailToken, emailUnsubscribeToken)
	return err
}

const unsubscribeBySMSToken = `-- name: UnsubscribeBySMSToken :exec
UPDATE notification_preferences SET sms_enabled = FALSE, updated_at = NOW()
WHERE sms_unsubscribe_token = $1
`

func (q *Queries) UnsubscribeBySMSToken(ctx context.Context, smsUnsubscribeToken pgtype.UUID) error {
	_, err := q.db.Exec(ctx, unsubscribeBySMSToken, smsUnsubscribeToken)
	return err
}

const unsubscribeSMSByPhoneNumber = `-- name: UnsubscribeSMSByPhoneNumber :exec
UPDATE notification_preferences SET sms_enabled = FALSE, updated_at = NOW()
WHERE user_id = (SELECT id FROM users WHERE phone_number = $1 LIMIT 1)
`

func (q *Queries) UnsubscribeSMSByPhoneNumber(ctx context.Context, phoneNumber pgtype.Text) error {
	_, err := q.db.Exec(ctx, unsubscribeSMSByPhoneNumber, phoneNumber)
	return err
}

const upsertNotificationPreferences = `-- name: UpsertNotificationPreferences :one
INSERT INTO notification_preferences (user_id, email_enabled, sms_enabled, preferred_categories, digest_format, email_style)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id) DO UPDATE SET
    email_enabled = EXCLUDED.email_enabled,
    sms_enabled = EXCLUDED.sms_enabled,
    preferred_categories = EXCLUDED.preferred_categories,
    digest_format = EXCLUDED.digest_format,
    email_style = EXCLUDED.email_style,
    updated_at = NOW()
RETURNING id, user_id, email_enabled, sms_enabled, email_unsubscribe_token, sms_unsubscribe_token, created_at, updated_at, preferred_categories, digest_format, email_style
`

type UpsertNotificationPreferencesParams struct {
	UserID              pgtype.UUID
	EmailEnabled        bool
	SmsEnabled          bool
	PreferredCategories []string
	DigestFormat        string
	EmailStyle          string
}

func (q *Queries) UpsertNotificationPreferences(ctx context.Context, arg UpsertNotificationPreferencesParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertNotificationPreferences,
		arg.UserID,
		arg.EmailEnabled,
		arg.SmsEnabled,
		arg.PreferredCategories,
		arg.DigestFormat,
		arg.EmailStyle,
	)
	var i NotificationPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EmailEnabled,
		&i.SmsEnabled,
		&i.EmailUnsubscribeToken,
		&i.SmsUnsubscribeToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PreferredCategories,
		&i.DigestFormat,
		&i.EmailStyle,
	)
	return i, err
}
