// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: places.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlace = `-- name: CreatePlace :one
INSERT INTO places (
    name, is_food, is_drink, cuisine, bar_type,
    address, city, state, zip,
    latitude, longitude, phone, website, hours,
    description, review, image_url, tags, price_level
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13, $14,
    $15, $16, $17, $18, $19
) RETURNING id, name, is_food, is_drink, cuisine, bar_type, address, city, state, zip, latitude, longitude, phone, website, hours, description, review, image_url, tags, price_level, created_at, updated_at
`

type CreatePlaceParams struct {
	Name        string
	IsFood      bool
	IsDrink     bool
	Cuisine     pgtype.Text
	BarType     pgtype.Text
	Address     pgtype.Text
	City        pgtype.Text
	State       pgtype.Text
	Zip         pgtype.Text
	Latitude    float64
	Longitude   float64
	Phone       pgtype.Text
	Website     pgtype.Text
	Hours       pgtype.Text
	Description pgtype.Text
	Review      pgtype.Text
	ImageUrl    pgtype.Text
	Tags        []string
	PriceLevel  pgtype.Int4
}

func (q *Queries) CreatePlace(ctx context.Context, arg CreatePlaceParams) (Place, error) {
	row := q.db.QueryRow(ctx, createPlace,
		arg.Name,
		arg.IsFood,
		arg.IsDrink,
		arg.Cuisine,
		arg.BarType,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Latitude,
		arg.Longitude,
		arg.Phone,
		arg.Website,
		arg.Hours,
		arg.Description,
		arg.Review,
		arg.ImageUrl,
		arg.Tags,
		arg.PriceLevel,
	)
	var i Place
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsFood,
		&i.IsDrink,
		&i.Cuisine,
		&i.BarType,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.Phone,
		&i.Website,
		&i.Hours,
		&i.Description,
		&i.Review,
		&i.ImageUrl,
		&i.Tags,
		&i.PriceLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlace = `-- name: DeletePlace :exec
DELETE FROM places WHERE id = $1
`

func (q *Queries) DeletePlace(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePlace, id)
	return err
}

const getPlace = `-- name: GetPlace :one
SELECT id, name, is_food, is_drink, cuisine, bar_type, address, city, state, zip, latitude, longitude, phone, website, hours, description, review, image_url, tags, price_level, created_at, updated_at FROM places WHERE id = $1
`

func (q *Queries) GetPlace(ctx context.Context, id pgtype.UUID) (Place, error) {
	row := q.db.QueryRow(ctx, getPlace, id)
	var i Place
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsFood,
		&i.IsDrink,
		&i.Cuisine,
		&i.BarType,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.Phone,
		&i.Website,
		&i.Hours,
		&i.Description,
		&i.Review,
		&i.ImageUrl,
		&i.Tags,
		&i.PriceLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlacesByLocation = `-- name: ListPlacesByLocation :many
SELECT id, name, is_food, is_drink, cuisine, bar_type, address, city, state, zip, latitude, longitude, phone, website, hours, description, review, image_url, tags, price_level, created_at, updated_at
FROM places
WHERE ST_DWithin(
    ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography,
    ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography,
    $3::float
)
AND (NOT $4::bool OR is_food)
AND (NOT $5::bool OR is_drink)
AND (cardinality($6::text[]) = 0 OR (is_food AND cuisine = ANY($6::text[])))
AND (cardinality($7::text[]) = 0 OR (is_drink AND bar_type = ANY($7::text[])))
AND ($8::int IS NULL OR price_level >= $8::int)
AND ($9::int IS NULL OR price_level <= $9::int)
AND ($10::text IS NULL
     OR name ILIKE '%' || $10::text || '%'
     OR description ILIKE '%' || $10::text || '%'
     OR city ILIKE '%' || $10::text || '%')
ORDER BY ST_Distance(
    ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography,
    ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography
) ASC
`

type ListPlacesByLocationParams struct {
	Lng          float64
	Lat          float64
	RadiusMeters float64
	RequireFood  bool
	RequireDrink bool
	Cuisines     []string
	BarTypes     []string
	MinPrice     pgtype.Int4
	MaxPrice     pgtype.Int4
	Search       pgtype.Text
}

func (q *Queries) ListPlacesByLocation(ctx context.Context, arg ListPlacesByLocationParams) ([]Place, error) {
	rows, err := q.db.Query(ctx, listPlacesByLocation,
		arg.Lng,
		arg.Lat,
		arg.RadiusMeters,
		arg.RequireFood,
		arg.RequireDrink,
		arg.Cuisines,
		arg.BarTypes,
		arg.MinPrice,
		arg.MaxPrice,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Place
	for rows.Next() {
		var i Place
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsFood,
			&i.IsDrink,
			&i.Cuisine,
			&i.BarType,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Latitude,
			&i.Longitude,
			&i.Phone,
			&i.Website,
			&i.Hours,
			&i.Description,
			&i.Review,
			&i.ImageUrl,
			&i.Tags,
			&i.PriceLevel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlace = `-- name: UpdatePlace :one
UPDATE places SET
    name = $2,
    is_food = $3,
    is_drink = $4,
    cuisine = $5,
    bar_type = $6,
    address = $7,
    city = $8,
    state = $9,
    zip = $10,
    latitude = $11,
    longitude = $12,
    phone = $13,
    website = $14,
    hours = $15,
    description = $16,
    review = $17,
    image_url = $18,
    tags = $19,
    price_level = $20,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, is_food, is_drink, cuisine, bar_type, address, city, state, zip, latitude, longitude, phone, website, hours, description, review, image_url, tags, price_level, created_at, updated_at
`

type UpdatePlaceParams struct {
	ID          pgtype.UUID
	Name        string
	IsFood      bool
	IsDrink     bool
	Cuisine     pgtype.Text
	BarType     pgtype.Text
	Address     pgtype.Text
	City        pgtype.Text
	State       pgtype.Text
	Zip         pgtype.Text
	Latitude    float64
	Longitude   float64
	Phone       pgtype.Text
	Website     pgtype.Text
	Hours       pgtype.Text
	Description pgtype.Text
	Review      pgtype.Text
	ImageUrl    pgtype.Text
	Tags        []string
	PriceLevel  pgtype.Int4
}

func (q *Queries) UpdatePlace(ctx context.Context, arg UpdatePlaceParams) (Place, error) {
	row := q.db.QueryRow(ctx, updatePlace,
		arg.ID,
		arg.Name,
		arg.IsFood,
		arg.IsDrink,
		arg.Cuisine,
		arg.BarType,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Latitude,
		arg.Longitude,
		arg.Phone,
		arg.Website,
		arg.Hours,
		arg.Description,
		arg.Review,
		arg.ImageUrl,
		arg.Tags,
		arg.PriceLevel,
	)
	var i Place
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsFood,
		&i.IsDrink,
		&i.Cuisine,
		&i.BarType,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.Phone,
		&i.Website,
		&i.Hours,
		&i.Description,
		&i.Review,
		&i.ImageUrl,
		&i.Tags,
		&i.PriceLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
