// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: place_checkins.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkInPlace = `-- name: CheckInPlace :one
INSERT INTO place_checkins (user_id, place_id, user_latitude, user_longitude)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, place_id, checkin_date) DO NOTHING
RETURNING id, user_id, place_id, checkin_date, user_latitude, user_longitude, created_at
`

type CheckInPlaceParams struct {
	UserID        pgtype.UUID
	PlaceID       pgtype.UUID
	UserLatitude  float64
	UserLongitude float64
}

func (q *Queries) CheckInPlace(ctx context.Context, arg CheckInPlaceParams) (PlaceCheckin, error) {
	row := q.db.QueryRow(ctx, checkInPlace,
		arg.UserID,
		arg.PlaceID,
		arg.UserLatitude,
		arg.UserLongitude,
	)
	var i PlaceCheckin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlaceID,
		&i.CheckinDate,
		&i.UserLatitude,
		&i.UserLongitude,
		&i.CreatedAt,
	)
	return i, err
}

const getPlaceCheckInCounts = `-- name: GetPlaceCheckInCounts :one
SELECT
    COUNT(*)::bigint AS total_count,
    COUNT(DISTINCT user_id)::bigint AS unique_count
FROM place_checkins
WHERE place_id = $1
`

type GetPlaceCheckInCountsRow struct {
	TotalCount  int64
	UniqueCount int64
}

func (q *Queries) GetPlaceCheckInCounts(ctx context.Context, placeID pgtype.UUID) (GetPlaceCheckInCountsRow, error) {
	row := q.db.QueryRow(ctx, getPlaceCheckInCounts, placeID)
	var i GetPlaceCheckInCountsRow
	err := row.Scan(&i.TotalCount, &i.UniqueCount)
	return i, err
}

const getUserPlaceCheckInStats = `-- name: GetUserPlaceCheckInStats :one
SELECT
    COUNT(*)::bigint AS total_checkins,
    COUNT(DISTINCT c.place_id)::bigint AS unique_places,
    COUNT(DISTINCT CASE WHEN p.is_food THEN c.place_id END)::bigint AS unique_foods,
    COUNT(DISTINCT CASE WHEN p.is_drink AND p.bar_type = 'brewery' THEN c.place_id END)::bigint AS unique_breweries,
    COUNT(DISTINCT CASE WHEN p.is_drink AND p.bar_type = 'bar' THEN c.place_id END)::bigint AS unique_bars,
    MIN(c.checkin_date)::date AS first_checkin_date,
    MAX(c.checkin_date)::date AS last_checkin_date
FROM place_checkins c
JOIN places p ON p.id = c.place_id
WHERE c.user_id = $1
`

type GetUserPlaceCheckInStatsRow struct {
	TotalCheckins    int64
	UniquePlaces     int64
	UniqueFoods      int64
	UniqueBreweries  int64
	UniqueBars       int64
	FirstCheckinDate pgtype.Date
	LastCheckinDate  pgtype.Date
}

func (q *Queries) GetUserPlaceCheckInStats(ctx context.Context, userID pgtype.UUID) (GetUserPlaceCheckInStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserPlaceCheckInStats, userID)
	var i GetUserPlaceCheckInStatsRow
	err := row.Scan(
		&i.TotalCheckins,
		&i.UniquePlaces,
		&i.UniqueFoods,
		&i.UniqueBreweries,
		&i.UniqueBars,
		&i.FirstCheckinDate,
		&i.LastCheckinDate,
	)
	return i, err
}

const hasUserCheckedInPlaceToday = `-- name: HasUserCheckedInPlaceToday :one
SELECT EXISTS(
    SELECT 1 FROM place_checkins
    WHERE user_id = $1 AND place_id = $2 AND checkin_date = CURRENT_DATE
) AS checked_in
`

type HasUserCheckedInPlaceTodayParams struct {
	UserID  pgtype.UUID
	PlaceID pgtype.UUID
}

func (q *Queries) HasUserCheckedInPlaceToday(ctx context.Context, arg HasUserCheckedInPlaceTodayParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserCheckedInPlaceToday, arg.UserID, arg.PlaceID)
	var checked_in bool
	err := row.Scan(&checked_in)
	return checked_in, err
}

const listUserPlaceCheckIns = `-- name: ListUserPlaceCheckIns :many
SELECT
    c.id,
    c.place_id,
    c.checkin_date,
    c.created_at,
    p.name AS place_name,
    p.is_food AS place_is_food,
    p.is_drink AS place_is_drink,
    p.cuisine AS place_cuisine,
    p.bar_type AS place_bar_type,
    p.city AS place_city,
    p.image_url AS place_image_url
FROM place_checkins c
JOIN places p ON p.id = c.place_id
WHERE c.user_id = $1
ORDER BY c.checkin_date DESC, c.created_at DESC
`

type ListUserPlaceCheckInsRow struct {
	ID            pgtype.UUID
	PlaceID       pgtype.UUID
	CheckinDate   pgtype.Date
	CreatedAt     pgtype.Timestamptz
	PlaceName     string
	PlaceIsFood   bool
	PlaceIsDrink  bool
	PlaceCuisine  pgtype.Text
	PlaceBarType  pgtype.Text
	PlaceCity     pgtype.Text
	PlaceImageUrl pgtype.Text
}

func (q *Queries) ListUserPlaceCheckIns(ctx context.Context, userID pgtype.UUID) ([]ListUserPlaceCheckInsRow, error) {
	rows, err := q.db.Query(ctx, listUserPlaceCheckIns, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserPlaceCheckInsRow
	for rows.Next() {
		var i ListUserPlaceCheckInsRow
		if err := rows.Scan(
			&i.ID,
			&i.PlaceID,
			&i.CheckinDate,
			&i.CreatedAt,
			&i.PlaceName,
			&i.PlaceIsFood,
			&i.PlaceIsDrink,
			&i.PlaceCuisine,
			&i.PlaceBarType,
			&i.PlaceCity,
			&i.PlaceImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
