// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: planner.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSharedPlan = `-- name: CreateSharedPlan :one
INSERT INTO shared_plans (plan, created_by)
VALUES ($1, $2)
RETURNING token
`

type CreateSharedPlanParams struct {
	Plan      []byte
	CreatedBy pgtype.UUID
}

func (q *Queries) CreateSharedPlan(ctx context.Context, arg CreateSharedPlanParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createSharedPlan, arg.Plan, arg.CreatedBy)
	var token pgtype.UUID
	err := row.Scan(&token)
	return token, err
}

const getLatestDailyPlan = `-- name: GetLatestDailyPlan :one
SELECT week_of, plan, generated_at FROM daily_plans
WHERE user_id = $1
ORDER BY week_of DESC
LIMIT 1
`

type GetLatestDailyPlanRow struct {
	WeekOf      pgtype.Date
	Plan        []byte
	GeneratedAt pgtype.Timestamptz
}

func (q *Queries) GetLatestDailyPlan(ctx context.Context, userID pgtype.UUID) (GetLatestDailyPlanRow, error) {
	row := q.db.QueryRow(ctx, getLatestDailyPlan, userID)
	var i GetLatestDailyPlanRow
	err := row.Scan(&i.WeekOf, &i.Plan, &i.GeneratedAt)
	return i, err
}

const getSharedPlan = `-- name: GetSharedPlan :one
SELECT plan, created_at FROM shared_plans WHERE token = $1
`

type GetSharedPlanRow struct {
	Plan      []byte
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetSharedPlan(ctx context.Context, token pgtype.UUID) (GetSharedPlanRow, error) {
	row := q.db.QueryRow(ctx, getSharedPlan, token)
	var i GetSharedPlanRow
	err := row.Scan(&i.Plan, &i.CreatedAt)
	return i, err
}

const listPlannerEventsForUser = `-- name: ListPlannerEventsForUser :many
WITH u AS (
    SELECT preference_vector FROM user_preferences WHERE user_id = $6
)
SELECT e.id, e.external_id, e.source, e.title, e.description, e.venue_name, e.address, e.city, e.state, e.zip, e.latitude, e.longitude, e.start_time, e.end_time, e.image_url, e.ticket_url, e.price_min, e.price_max, e.submitted_by, e.created_at, e.updated_at, e.manually_edited, e.venue_id, e.categories, e.series_id, e.is_free, e.is_featured, e.featured_at, e.featured_by,
       ST_Distance(
           ST_SetSRID(ST_MakePoint(e.longitude, e.latitude), 4326)::geography,
           ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography
       )::float AS distance_meters,
       CASE WHEN (SELECT preference_vector FROM u) IS NOT NULL
            THEN (1 - (ee.embedding <=> (SELECT preference_vector FROM u)))::float
            ELSE NULL END AS pref_score
FROM events e
LEFT JOIN event_embeddings ee ON ee.event_id = e.id
WHERE ST_DWithin(
    ST_SetSRID(ST_MakePoint(e.longitude, e.latitude), 4326)::geography,
    ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography,
    $3::float
)
AND e.start_time >= $4::timestamptz
AND e.start_time < $5::timestamptz
ORDER BY (e.start_time AT TIME ZONE 'America/New_York')::date ASC, e.start_time ASC
`

type ListPlannerEventsForUserParams struct {
	Lng          float64
	Lat          float64
	RadiusMeters float64
	StartDate    pgtype.Timestamptz
	EndDate      pgtype.Timestamptz
	UserID       pgtype.UUID
}

type ListPlannerEventsForUserRow struct {
	ID             pgtype.UUID
	ExternalID     pgtype.Text
	Source         string
	Title          string
	Description    pgtype.Text
	VenueName      pgtype.Text
	Address        pgtype.Text
	City           pgtype.Text
	State          pgtype.Text
	Zip            pgtype.Text
	Latitude       float64
	Longitude      float64
	StartTime      pgtype.Timestamptz
	EndTime        pgtype.Timestamptz
	ImageUrl       pgtype.Text
	TicketUrl      pgtype.Text
	PriceMin       pgtype.Numeric
	PriceMax       pgtype.Numeric
	SubmittedBy    pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ManuallyEdited bool
	VenueID        pgtype.UUID
	Categories     []string
	SeriesID       pgtype.UUID
	IsFree         bool
	IsFeatured     bool
	FeaturedAt     pgtype.Timestamptz
	FeaturedBy     pgtype.UUID
	DistanceMeters float64
	PrefScore      interface{}
}

// Events within the user's radius and the plan window, annotated with distance
// (meters) and an optional preference score (cosine similarity to the user's
// preference vector, NULL when the user has no vector or the event has no
// embedding). LEFT JOIN keeps cold-start users covered. Ordered by ET day then
// start time; the planner re-ranks within each day before persisting.
func (q *Queries) ListPlannerEventsForUser(ctx context.Context, arg ListPlannerEventsForUserParams) ([]ListPlannerEventsForUserRow, error) {
	rows, err := q.db.Query(ctx, listPlannerEventsForUser,
		arg.Lng,
		arg.Lat,
		arg.RadiusMeters,
		arg.StartDate,
		arg.EndDate,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlannerEventsForUserRow
	for rows.Next() {
		var i ListPlannerEventsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Source,
			&i.Title,
			&i.Description,
			&i.VenueName,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Latitude,
			&i.Longitude,
			&i.StartTime,
			&i.EndTime,
			&i.ImageUrl,
			&i.TicketUrl,
			&i.PriceMin,
			&i.PriceMax,
			&i.SubmittedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ManuallyEdited,
			&i.VenueID,
			&i.Categories,
			&i.SeriesID,
			&i.IsFree,
			&i.IsFeatured,
			&i.FeaturedAt,
			&i.FeaturedBy,
			&i.DistanceMeters,
			&i.PrefScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDailyPlan = `-- name: UpsertDailyPlan :exec
INSERT INTO daily_plans (user_id, week_of, plan, generated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (user_id, week_of) DO UPDATE SET
    plan = EXCLUDED.plan,
    generated_at = NOW()
`

type UpsertDailyPlanParams struct {
	UserID pgtype.UUID
	WeekOf pgtype.Date
	Plan   []byte
}

func (q *Queries) UpsertDailyPlan(ctx context.Context, arg UpsertDailyPlanParams) error {
	_, err := q.db.Exec(ctx, upsertDailyPlan, arg.UserID, arg.WeekOf, arg.Plan)
	return err
}
