// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveApplication = `-- name: ApproveApplication :one
UPDATE author_applications SET
    status = 'approved',
    reviewed_at = NOW(),
    reviewed_by = $2,
    review_notes = $3
WHERE id = $1
RETURNING id, clerk_id, full_name, email, bio, experience, status, submitted_at, reviewed_at, reviewed_by, review_notes
`

type ApproveApplicationParams struct {
	ID          pgtype.UUID
	ReviewedBy  pgtype.Text
	ReviewNotes pgtype.Text
}

func (q *Queries) ApproveApplication(ctx context.Context, arg ApproveApplicationParams) (AuthorApplication, error) {
	row := q.db.QueryRow(ctx, approveApplication, arg.ID, arg.ReviewedBy, arg.ReviewNotes)
	var i AuthorApplication
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.FullName,
		&i.Email,
		&i.Bio,
		&i.Experience,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.ReviewNotes,
	)
	return i, err
}

const countEventsByLocation = `-- name: CountEventsByLocation :one
SELECT COUNT(*)
FROM events
WHERE ST_DWithin(
    ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography,
    ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography,
    $3::float
)
AND start_time >= $4::timestamptz
AND start_time < $5::timestamptz
AND ($6::text IS NULL OR category = $6::text)
AND ($7::text IS NULL OR venue_name = $7::text)
AND ($8::text IS NULL OR title ILIKE '%' || $8::text || '%' OR venue_name ILIKE '%' || $8::text || '%')
`

type CountEventsByLocationParams struct {
	Lng          float64
	Lat          float64
	RadiusMeters float64
	StartDate    pgtype.Timestamptz
	EndDate      pgtype.Timestamptz
	Category     pgtype.Text
	VenueName    pgtype.Text
	Search       pgtype.Text
}

func (q *Queries) CountEventsByLocation(ctx context.Context, arg CountEventsByLocationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEventsByLocation,
		arg.Lng,
		arg.Lat,
		arg.RadiusMeters,
		arg.StartDate,
		arg.EndDate,
		arg.Category,
		arg.VenueName,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthorApplication = `-- name: CreateAuthorApplication :one
INSERT INTO author_applications (clerk_id, full_name, email, bio, experience)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, clerk_id, full_name, email, bio, experience, status, submitted_at, reviewed_at, reviewed_by, review_notes
`

type CreateAuthorApplicationParams struct {
	ClerkID    string
	FullName   string
	Email      string
	Bio        string
	Experience string
}

func (q *Queries) CreateAuthorApplication(ctx context.Context, arg CreateAuthorApplicationParams) (AuthorApplication, error) {
	row := q.db.QueryRow(ctx, createAuthorApplication,
		arg.ClerkID,
		arg.FullName,
		arg.Email,
		arg.Bio,
		arg.Experience,
	)
	var i AuthorApplication
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.FullName,
		&i.Email,
		&i.Bio,
		&i.Experience,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.ReviewNotes,
	)
	return i, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    source, title, description, venue_name, address, city, state, zip,
    latitude, longitude, start_time, end_time, category, image_url,
    ticket_url, price_min, price_max, submitted_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14,
    $15, $16, $17, $18
) RETURNING id, external_id, source, title, description, venue_name, address, city, state, zip, latitude, longitude, start_time, end_time, category, image_url, ticket_url, price_min, price_max, submitted_by, created_at, updated_at
`

type CreateEventParams struct {
	Source      string
	Title       string
	Description pgtype.Text
	VenueName   pgtype.Text
	Address     pgtype.Text
	City        pgtype.Text
	State       pgtype.Text
	Zip         pgtype.Text
	Latitude    float64
	Longitude   float64
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	Category    pgtype.Text
	ImageUrl    pgtype.Text
	TicketUrl   pgtype.Text
	PriceMin    pgtype.Numeric
	PriceMax    pgtype.Numeric
	SubmittedBy pgtype.UUID
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Source,
		arg.Title,
		arg.Description,
		arg.VenueName,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Latitude,
		arg.Longitude,
		arg.StartTime,
		arg.EndTime,
		arg.Category,
		arg.ImageUrl,
		arg.TicketUrl,
		arg.PriceMin,
		arg.PriceMax,
		arg.SubmittedBy,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Source,
		&i.Title,
		&i.Description,
		&i.VenueName,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.StartTime,
		&i.EndTime,
		&i.Category,
		&i.ImageUrl,
		&i.TicketUrl,
		&i.PriceMin,
		&i.PriceMax,
		&i.SubmittedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const deletePastEvents = `-- name: DeletePastEvents :execrows
DELETE FROM events
WHERE start_time < NOW()::date
`

func (q *Queries) DeletePastEvents(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deletePastEvents)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAuthorApplication = `-- name: GetAuthorApplication :one
SELECT id, clerk_id, full_name, email, bio, experience, status, submitted_at, reviewed_at, reviewed_by, review_notes FROM author_applications WHERE id = $1
`

func (q *Queries) GetAuthorApplication(ctx context.Context, id pgtype.UUID) (AuthorApplication, error) {
	row := q.db.QueryRow(ctx, getAuthorApplication, id)
	var i AuthorApplication
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.FullName,
		&i.Email,
		&i.Bio,
		&i.Experience,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.ReviewNotes,
	)
	return i, err
}

const getAuthorApplicationByClerkID = `-- name: GetAuthorApplicationByClerkID :one
SELECT id, clerk_id, full_name, email, bio, experience, status, submitted_at, reviewed_at, reviewed_by, review_notes FROM author_applications
WHERE clerk_id = $1
ORDER BY submitted_at DESC
LIMIT 1
`

func (q *Queries) GetAuthorApplicationByClerkID(ctx context.Context, clerkID string) (AuthorApplication, error) {
	row := q.db.QueryRow(ctx, getAuthorApplicationByClerkID, clerkID)
	var i AuthorApplication
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.FullName,
		&i.Email,
		&i.Bio,
		&i.Experience,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.ReviewNotes,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, external_id, source, title, description, venue_name, address, city, state, zip, latitude, longitude, start_time, end_time, category, image_url, ticket_url, price_min, price_max, submitted_by, created_at, updated_at FROM events WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Source,
		&i.Title,
		&i.Description,
		&i.VenueName,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.StartTime,
		&i.EndTime,
		&i.Category,
		&i.ImageUrl,
		&i.TicketUrl,
		&i.PriceMin,
		&i.PriceMax,
		&i.SubmittedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByClerkID = `-- name: GetUserByClerkID :one
SELECT id, clerk_id, username, email, default_latitude, default_longitude, default_radius_miles, created_at, updated_at FROM users WHERE clerk_id = $1
`

func (q *Queries) GetUserByClerkID(ctx context.Context, clerkID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByClerkID, clerkID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Username,
		&i.Email,
		&i.DefaultLatitude,
		&i.DefaultLongitude,
		&i.DefaultRadiusMiles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, clerk_id, username, email, default_latitude, default_longitude, default_radius_miles, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Username,
		&i.Email,
		&i.DefaultLatitude,
		&i.DefaultLongitude,
		&i.DefaultRadiusMiles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDistinctVenues = `-- name: ListDistinctVenues :many
SELECT DISTINCT ON (venue_name)
    venue_name, address, city, state, zip, latitude, longitude
FROM events
WHERE venue_name IS NOT NULL AND venue_name != ''
AND ST_DWithin(
    ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography,
    ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography,
    $3::float
)
ORDER BY venue_name ASC
`

type ListDistinctVenuesParams struct {
	Lng          float64
	Lat          float64
	RadiusMeters float64
}

type ListDistinctVenuesRow struct {
	VenueName pgtype.Text
	Address   pgtype.Text
	City      pgtype.Text
	State     pgtype.Text
	Zip       pgtype.Text
	Latitude  float64
	Longitude float64
}

func (q *Queries) ListDistinctVenues(ctx context.Context, arg ListDistinctVenuesParams) ([]ListDistinctVenuesRow, error) {
	rows, err := q.db.Query(ctx, listDistinctVenues, arg.Lng, arg.Lat, arg.RadiusMeters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDistinctVenuesRow
	for rows.Next() {
		var i ListDistinctVenuesRow
		if err := rows.Scan(
			&i.VenueName,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByLocation = `-- name: ListEventsByLocation :many
SELECT id, external_id, source, title, description, venue_name, address, city, state, zip, latitude, longitude, start_time, end_time, category, image_url, ticket_url, price_min, price_max, submitted_by, created_at, updated_at
FROM events
WHERE ST_DWithin(
    ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography,
    ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography,
    $3::float
)
AND start_time >= $4::timestamptz
AND start_time < $5::timestamptz
AND ($6::text IS NULL OR category = $6::text)
AND ($7::text IS NULL OR venue_name = $7::text)
AND ($8::text IS NULL OR title ILIKE '%' || $8::text || '%' OR venue_name ILIKE '%' || $8::text || '%')
ORDER BY ST_Distance(
    ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography,
    ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography
) ASC, start_time ASC
LIMIT $10 OFFSET $9
`

type ListEventsByLocationParams struct {
	Lng          float64
	Lat          float64
	RadiusMeters float64
	StartDate    pgtype.Timestamptz
	EndDate      pgtype.Timestamptz
	Category     pgtype.Text
	VenueName    pgtype.Text
	Search       pgtype.Text
	EventOffset  int32
	EventLimit   int32
}

func (q *Queries) ListEventsByLocation(ctx context.Context, arg ListEventsByLocationParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByLocation,
		arg.Lng,
		arg.Lat,
		arg.RadiusMeters,
		arg.StartDate,
		arg.EndDate,
		arg.Category,
		arg.VenueName,
		arg.Search,
		arg.EventOffset,
		arg.EventLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Source,
			&i.Title,
			&i.Description,
			&i.VenueName,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Latitude,
			&i.Longitude,
			&i.StartTime,
			&i.EndTime,
			&i.Category,
			&i.ImageUrl,
			&i.TicketUrl,
			&i.PriceMin,
			&i.PriceMax,
			&i.SubmittedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingApplications = `-- name: ListPendingApplications :many
SELECT id, clerk_id, full_name, email, bio, experience, status, submitted_at, reviewed_at, reviewed_by, review_notes FROM author_applications
WHERE status = 'pending'
ORDER BY submitted_at ASC
`

func (q *Queries) ListPendingApplications(ctx context.Context) ([]AuthorApplication, error) {
	rows, err := q.db.Query(ctx, listPendingApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthorApplication
	for rows.Next() {
		var i AuthorApplication
		if err := rows.Scan(
			&i.ID,
			&i.ClerkID,
			&i.FullName,
			&i.Email,
			&i.Bio,
			&i.Experience,
			&i.Status,
			&i.SubmittedAt,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.ReviewNotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedEvents = `-- name: ListSavedEvents :many
SELECT e.id, e.external_id, e.source, e.title, e.description, e.venue_name, e.address, e.city, e.state, e.zip, e.latitude, e.longitude, e.start_time, e.end_time, e.category, e.image_url, e.ticket_url, e.price_min, e.price_max, e.submitted_by, e.created_at, e.updated_at
FROM events e
JOIN saved_events se ON se.event_id = e.id
WHERE se.user_id = $1
ORDER BY e.start_time ASC
`

func (q *Queries) ListSavedEvents(ctx context.Context, userID pgtype.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, listSavedEvents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Source,
			&i.Title,
			&i.Description,
			&i.VenueName,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Latitude,
			&i.Longitude,
			&i.StartTime,
			&i.EndTime,
			&i.Category,
			&i.ImageUrl,
			&i.TicketUrl,
			&i.PriceMin,
			&i.PriceMax,
			&i.SubmittedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectApplication = `-- name: RejectApplication :one
UPDATE author_applications SET
    status = 'rejected',
    reviewed_at = NOW(),
    reviewed_by = $2,
    review_notes = $3
WHERE id = $1
RETURNING id, clerk_id, full_name, email, bio, experience, status, submitted_at, reviewed_at, reviewed_by, review_notes
`

type RejectApplicationParams struct {
	ID          pgtype.UUID
	ReviewedBy  pgtype.Text
	ReviewNotes pgtype.Text
}

func (q *Queries) RejectApplication(ctx context.Context, arg RejectApplicationParams) (AuthorApplication, error) {
	row := q.db.QueryRow(ctx, rejectApplication, arg.ID, arg.ReviewedBy, arg.ReviewNotes)
	var i AuthorApplication
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.FullName,
		&i.Email,
		&i.Bio,
		&i.Experience,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.ReviewNotes,
	)
	return i, err
}

const saveEvent = `-- name: SaveEvent :one
INSERT INTO saved_events (user_id, event_id)
VALUES ($1, $2)
ON CONFLICT (user_id, event_id) DO NOTHING
RETURNING id, user_id, event_id, created_at
`

type SaveEventParams struct {
	UserID  pgtype.UUID
	EventID pgtype.UUID
}

func (q *Queries) SaveEvent(ctx context.Context, arg SaveEventParams) (SavedEvent, error) {
	row := q.db.QueryRow(ctx, saveEvent, arg.UserID, arg.EventID)
	var i SavedEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.CreatedAt,
	)
	return i, err
}

const unsaveEvent = `-- name: UnsaveEvent :exec
DELETE FROM saved_events WHERE user_id = $1 AND event_id = $2
`

type UnsaveEventParams struct {
	UserID  pgtype.UUID
	EventID pgtype.UUID
}

func (q *Queries) UnsaveEvent(ctx context.Context, arg UnsaveEventParams) error {
	_, err := q.db.Exec(ctx, unsaveEvent, arg.UserID, arg.EventID)
	return err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events SET
    title = $2,
    description = $3,
    venue_name = $4,
    address = $5,
    city = $6,
    state = $7,
    zip = $8,
    latitude = $9,
    longitude = $10,
    start_time = $11,
    end_time = $12,
    category = $13,
    image_url = $14,
    ticket_url = $15,
    price_min = $16,
    price_max = $17,
    updated_at = NOW()
WHERE id = $1
RETURNING id, external_id, source, title, description, venue_name, address, city, state, zip, latitude, longitude, start_time, end_time, category, image_url, ticket_url, price_min, price_max, submitted_by, created_at, updated_at
`

type UpdateEventParams struct {
	ID          pgtype.UUID
	Title       string
	Description pgtype.Text
	VenueName   pgtype.Text
	Address     pgtype.Text
	City        pgtype.Text
	State       pgtype.Text
	Zip         pgtype.Text
	Latitude    float64
	Longitude   float64
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	Category    pgtype.Text
	ImageUrl    pgtype.Text
	TicketUrl   pgtype.Text
	PriceMin    pgtype.Numeric
	PriceMax    pgtype.Numeric
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.VenueName,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Latitude,
		arg.Longitude,
		arg.StartTime,
		arg.EndTime,
		arg.Category,
		arg.ImageUrl,
		arg.TicketUrl,
		arg.PriceMin,
		arg.PriceMax,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Source,
		&i.Title,
		&i.Description,
		&i.VenueName,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.StartTime,
		&i.EndTime,
		&i.Category,
		&i.ImageUrl,
		&i.TicketUrl,
		&i.PriceMin,
		&i.PriceMax,
		&i.SubmittedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserSettings = `-- name: UpdateUserSettings :one
UPDATE users SET
    default_latitude = $2,
    default_longitude = $3,
    default_radius_miles = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, clerk_id, username, email, default_latitude, default_longitude, default_radius_miles, created_at, updated_at
`

type UpdateUserSettingsParams struct {
	ID                 pgtype.UUID
	DefaultLatitude    pgtype.Float8
	DefaultLongitude   pgtype.Float8
	DefaultRadiusMiles pgtype.Int4
}

func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserSettings,
		arg.ID,
		arg.DefaultLatitude,
		arg.DefaultLongitude,
		arg.DefaultRadiusMiles,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Username,
		&i.Email,
		&i.DefaultLatitude,
		&i.DefaultLongitude,
		&i.DefaultRadiusMiles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertExternalEvent = `-- name: UpsertExternalEvent :one
INSERT INTO events (
    external_id, source, title, description, venue_name, address, city, state, zip,
    latitude, longitude, start_time, end_time, category, image_url,
    ticket_url, price_min, price_max
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18)
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL
DO UPDATE SET
    title=EXCLUDED.title, description=EXCLUDED.description,
    venue_name=EXCLUDED.venue_name, address=EXCLUDED.address,
    city=EXCLUDED.city, state=EXCLUDED.state, zip=EXCLUDED.zip,
    latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude,
    start_time=EXCLUDED.start_time, end_time=EXCLUDED.end_time,
    category=EXCLUDED.category, image_url=EXCLUDED.image_url,
    ticket_url=EXCLUDED.ticket_url, price_min=EXCLUDED.price_min,
    price_max=EXCLUDED.price_max, updated_at=NOW()
RETURNING id, external_id, source, title, description, venue_name, address, city, state, zip, latitude, longitude, start_time, end_time, category, image_url, ticket_url, price_min, price_max, submitted_by, created_at, updated_at
`

type UpsertExternalEventParams struct {
	ExternalID  pgtype.Text
	Source      string
	Title       string
	Description pgtype.Text
	VenueName   pgtype.Text
	Address     pgtype.Text
	City        pgtype.Text
	State       pgtype.Text
	Zip         pgtype.Text
	Latitude    float64
	Longitude   float64
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	Category    pgtype.Text
	ImageUrl    pgtype.Text
	TicketUrl   pgtype.Text
	PriceMin    pgtype.Numeric
	PriceMax    pgtype.Numeric
}

func (q *Queries) UpsertExternalEvent(ctx context.Context, arg UpsertExternalEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, upsertExternalEvent,
		arg.ExternalID,
		arg.Source,
		arg.Title,
		arg.Description,
		arg.VenueName,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Latitude,
		arg.Longitude,
		arg.StartTime,
		arg.EndTime,
		arg.Category,
		arg.ImageUrl,
		arg.TicketUrl,
		arg.PriceMin,
		arg.PriceMax,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Source,
		&i.Title,
		&i.Description,
		&i.VenueName,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.StartTime,
		&i.EndTime,
		&i.Category,
		&i.ImageUrl,
		&i.TicketUrl,
		&i.PriceMin,
		&i.PriceMax,
		&i.SubmittedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (clerk_id, username, email)
VALUES ($1, $2, $3)
ON CONFLICT (clerk_id) DO UPDATE SET
    username = COALESCE(EXCLUDED.username, users.username),
    email = COALESCE(EXCLUDED.email, users.email),
    updated_at = NOW()
RETURNING id, clerk_id, username, email, default_latitude, default_longitude, default_radius_miles, created_at, updated_at
`

type UpsertUserParams struct {
	ClerkID  string
	Username pgtype.Text
	Email    pgtype.Text
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.ClerkID, arg.Username, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Username,
		&i.Email,
		&i.DefaultLatitude,
		&i.DefaultLongitude,
		&i.DefaultRadiusMiles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
