// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveApplication = `-- name: ApproveApplication :one
UPDATE author_applications SET
    status = 'approved',
    reviewed_at = NOW(),
    reviewed_by = $2,
    review_notes = $3
WHERE id = $1
RETURNING id, clerk_id, full_name, email, bio, experience, status, submitted_at, reviewed_at, reviewed_by, review_notes
`

type ApproveApplicationParams struct {
	ID          pgtype.UUID
	ReviewedBy  pgtype.Text
	ReviewNotes pgtype.Text
}

func (q *Queries) ApproveApplication(ctx context.Context, arg ApproveApplicationParams) (AuthorApplication, error) {
	row := q.db.QueryRow(ctx, approveApplication, arg.ID, arg.ReviewedBy, arg.ReviewNotes)
	var i AuthorApplication
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.FullName,
		&i.Email,
		&i.Bio,
		&i.Experience,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.ReviewNotes,
	)
	return i, err
}

const approveEditSuggestion = `-- name: ApproveEditSuggestion :one
UPDATE edit_suggestions SET
    status = 'approved',
    reviewed_at = NOW(),
    reviewed_by = $2,
    review_notes = $3
WHERE id = $1
RETURNING id, target_type, target_id, submitted_by, proposed_changes, status, review_notes, reviewed_by, created_at, reviewed_at
`

type ApproveEditSuggestionParams struct {
	ID          pgtype.UUID
	ReviewedBy  pgtype.Text
	ReviewNotes pgtype.Text
}

func (q *Queries) ApproveEditSuggestion(ctx context.Context, arg ApproveEditSuggestionParams) (EditSuggestion, error) {
	row := q.db.QueryRow(ctx, approveEditSuggestion, arg.ID, arg.ReviewedBy, arg.ReviewNotes)
	var i EditSuggestion
	err := row.Scan(
		&i.ID,
		&i.TargetType,
		&i.TargetID,
		&i.SubmittedBy,
		&i.ProposedChanges,
		&i.Status,
		&i.ReviewNotes,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.ReviewedAt,
	)
	return i, err
}

const cleanOldDeletedExternalEvents = `-- name: CleanOldDeletedExternalEvents :execrows
DELETE FROM deleted_external_events
WHERE deleted_at < NOW() - INTERVAL '90 days'
`

func (q *Queries) CleanOldDeletedExternalEvents(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, cleanOldDeletedExternalEvents)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countEventsByLocation = `-- name: CountEventsByLocation :one
SELECT COUNT(*)
FROM events
WHERE ST_DWithin(
    ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography,
    ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography,
    $3::float
)
AND start_time >= $4::timestamptz
AND start_time < $5::timestamptz
AND ($6::text IS NULL OR $6::text = ANY(categories))
AND ($7::text IS NULL OR venue_name = $7::text)
AND ($8::uuid IS NULL OR venue_id = $8::uuid)
AND ($9::text IS NULL OR title ILIKE '%' || $9::text || '%' OR venue_name ILIKE '%' || $9::text || '%')
`

type CountEventsByLocationParams struct {
	Lng          float64
	Lat          float64
	RadiusMeters float64
	StartDate    pgtype.Timestamptz
	EndDate      pgtype.Timestamptz
	Category     pgtype.Text
	VenueName    pgtype.Text
	VenueID      pgtype.UUID
	Search       pgtype.Text
}

func (q *Queries) CountEventsByLocation(ctx context.Context, arg CountEventsByLocationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEventsByLocation,
		arg.Lng,
		arg.Lat,
		arg.RadiusMeters,
		arg.StartDate,
		arg.EndDate,
		arg.Category,
		arg.VenueName,
		arg.VenueID,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthorApplication = `-- name: CreateAuthorApplication :one
INSERT INTO author_applications (clerk_id, full_name, email, bio, experience)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, clerk_id, full_name, email, bio, experience, status, submitted_at, reviewed_at, reviewed_by, review_notes
`

type CreateAuthorApplicationParams struct {
	ClerkID    string
	FullName   string
	Email      string
	Bio        string
	Experience string
}

func (q *Queries) CreateAuthorApplication(ctx context.Context, arg CreateAuthorApplicationParams) (AuthorApplication, error) {
	row := q.db.QueryRow(ctx, createAuthorApplication,
		arg.ClerkID,
		arg.FullName,
		arg.Email,
		arg.Bio,
		arg.Experience,
	)
	var i AuthorApplication
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.FullName,
		&i.Email,
		&i.Bio,
		&i.Experience,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.ReviewNotes,
	)
	return i, err
}

const createEditSuggestion = `-- name: CreateEditSuggestion :one

INSERT INTO edit_suggestions (target_type, target_id, submitted_by, proposed_changes)
VALUES ($1, $2, $3, $4)
RETURNING id, target_type, target_id, submitted_by, proposed_changes, status, review_notes, reviewed_by, created_at, reviewed_at
`

type CreateEditSuggestionParams struct {
	TargetType      string
	TargetID        pgtype.UUID
	SubmittedBy     pgtype.UUID
	ProposedChanges []byte
}

// Edit Suggestions
func (q *Queries) CreateEditSuggestion(ctx context.Context, arg CreateEditSuggestionParams) (EditSuggestion, error) {
	row := q.db.QueryRow(ctx, createEditSuggestion,
		arg.TargetType,
		arg.TargetID,
		arg.SubmittedBy,
		arg.ProposedChanges,
	)
	var i EditSuggestion
	err := row.Scan(
		&i.ID,
		&i.TargetType,
		&i.TargetID,
		&i.SubmittedBy,
		&i.ProposedChanges,
		&i.Status,
		&i.ReviewNotes,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.ReviewedAt,
	)
	return i, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    source, title, description, venue_name, address, city, state, zip,
    latitude, longitude, start_time, end_time, categories, image_url,
    ticket_url, price_min, price_max, submitted_by, venue_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14,
    $15, $16, $17, $18, $19
) RETURNING id, external_id, source, title, description, venue_name, address, city, state, zip, latitude, longitude, start_time, end_time, image_url, ticket_url, price_min, price_max, submitted_by, created_at, updated_at, manually_edited, venue_id, categories
`

type CreateEventParams struct {
	Source      string
	Title       string
	Description pgtype.Text
	VenueName   pgtype.Text
	Address     pgtype.Text
	City        pgtype.Text
	State       pgtype.Text
	Zip         pgtype.Text
	Latitude    float64
	Longitude   float64
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	Categories  []string
	ImageUrl    pgtype.Text
	TicketUrl   pgtype.Text
	PriceMin    pgtype.Numeric
	PriceMax    pgtype.Numeric
	SubmittedBy pgtype.UUID
	VenueID     pgtype.UUID
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Source,
		arg.Title,
		arg.Description,
		arg.VenueName,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Latitude,
		arg.Longitude,
		arg.StartTime,
		arg.EndTime,
		arg.Categories,
		arg.ImageUrl,
		arg.TicketUrl,
		arg.PriceMin,
		arg.PriceMax,
		arg.SubmittedBy,
		arg.VenueID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Source,
		&i.Title,
		&i.Description,
		&i.VenueName,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.StartTime,
		&i.EndTime,
		&i.ImageUrl,
		&i.TicketUrl,
		&i.PriceMin,
		&i.PriceMax,
		&i.SubmittedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ManuallyEdited,
		&i.VenueID,
		&i.Categories,
	)
	return i, err
}

const createImage = `-- name: CreateImage :one
INSERT INTO images (user_id, r2_key, url, filename, content_type, size_bytes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, r2_key, url, filename, content_type, size_bytes, created_at
`

type CreateImageParams struct {
	UserID      pgtype.UUID
	R2Key       string
	Url         string
	Filename    string
	ContentType string
	SizeBytes   pgtype.Int8
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, createImage,
		arg.UserID,
		arg.R2Key,
		arg.Url,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.R2Key,
		&i.Url,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const createNotificationLog = `-- name: CreateNotificationLog :exec
INSERT INTO notification_log (user_id, channel, event_count, status, error_message)
VALUES ($1, $2, $3, $4, $5)
`

type CreateNotificationLogParams struct {
	UserID       pgtype.UUID
	Channel      string
	EventCount   int32
	Status       string
	ErrorMessage pgtype.Text
}

func (q *Queries) CreateNotificationLog(ctx context.Context, arg CreateNotificationLogParams) error {
	_, err := q.db.Exec(ctx, createNotificationLog,
		arg.UserID,
		arg.Channel,
		arg.EventCount,
		arg.Status,
		arg.ErrorMessage,
	)
	return err
}

const createVenue = `-- name: CreateVenue :one
INSERT INTO venues (name, address, city, state, zip, latitude, longitude, hours, description)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, address, city, state, zip, latitude, longitude, hours, description, created_at, updated_at
`

type CreateVenueParams struct {
	Name        string
	Address     pgtype.Text
	City        pgtype.Text
	State       pgtype.Text
	Zip         pgtype.Text
	Latitude    float64
	Longitude   float64
	Hours       pgtype.Text
	Description pgtype.Text
}

func (q *Queries) CreateVenue(ctx context.Context, arg CreateVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, createVenue,
		arg.Name,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Latitude,
		arg.Longitude,
		arg.Hours,
		arg.Description,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.Hours,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM images WHERE id = $1 AND user_id = $2
`

type DeleteImageParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteImage(ctx context.Context, arg DeleteImageParams) error {
	_, err := q.db.Exec(ctx, deleteImage, arg.ID, arg.UserID)
	return err
}

const deletePastEvents = `-- name: DeletePastEvents :execrows
DELETE FROM events
WHERE start_time < NOW()::date
`

func (q *Queries) DeletePastEvents(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deletePastEvents)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAuthorApplication = `-- name: GetAuthorApplication :one
SELECT id, clerk_id, full_name, email, bio, experience, status, submitted_at, reviewed_at, reviewed_by, review_notes FROM author_applications WHERE id = $1
`

func (q *Queries) GetAuthorApplication(ctx context.Context, id pgtype.UUID) (AuthorApplication, error) {
	row := q.db.QueryRow(ctx, getAuthorApplication, id)
	var i AuthorApplication
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.FullName,
		&i.Email,
		&i.Bio,
		&i.Experience,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.ReviewNotes,
	)
	return i, err
}

const getAuthorApplicationByClerkID = `-- name: GetAuthorApplicationByClerkID :one
SELECT id, clerk_id, full_name, email, bio, experience, status, submitted_at, reviewed_at, reviewed_by, review_notes FROM author_applications
WHERE clerk_id = $1
ORDER BY submitted_at DESC
LIMIT 1
`

func (q *Queries) GetAuthorApplicationByClerkID(ctx context.Context, clerkID string) (AuthorApplication, error) {
	row := q.db.QueryRow(ctx, getAuthorApplicationByClerkID, clerkID)
	var i AuthorApplication
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.FullName,
		&i.Email,
		&i.Bio,
		&i.Experience,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.ReviewNotes,
	)
	return i, err
}

const getEditSuggestion = `-- name: GetEditSuggestion :one
SELECT id, target_type, target_id, submitted_by, proposed_changes, status, review_notes, reviewed_by, created_at, reviewed_at FROM edit_suggestions WHERE id = $1
`

func (q *Queries) GetEditSuggestion(ctx context.Context, id pgtype.UUID) (EditSuggestion, error) {
	row := q.db.QueryRow(ctx, getEditSuggestion, id)
	var i EditSuggestion
	err := row.Scan(
		&i.ID,
		&i.TargetType,
		&i.TargetID,
		&i.SubmittedBy,
		&i.ProposedChanges,
		&i.Status,
		&i.ReviewNotes,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.ReviewedAt,
	)
	return i, err
}

const getEmailSubscriberByID = `-- name: GetEmailSubscriberByID :one
SELECT u.id, u.email, u.default_latitude, u.default_longitude, u.default_radius_miles,
       np.email_unsubscribe_token, np.preferred_categories
FROM users u
JOIN notification_preferences np ON np.user_id = u.id
WHERE u.id = $1
  AND np.email_enabled = TRUE
  AND u.email IS NOT NULL
  AND u.default_latitude IS NOT NULL
  AND u.default_longitude IS NOT NULL
`

type GetEmailSubscriberByIDRow struct {
	ID                    pgtype.UUID
	Email                 pgtype.Text
	DefaultLatitude       pgtype.Float8
	DefaultLongitude      pgtype.Float8
	DefaultRadiusMiles    pgtype.Int4
	EmailUnsubscribeToken pgtype.UUID
	PreferredCategories   []string
}

func (q *Queries) GetEmailSubscriberByID(ctx context.Context, id pgtype.UUID) (GetEmailSubscriberByIDRow, error) {
	row := q.db.QueryRow(ctx, getEmailSubscriberByID, id)
	var i GetEmailSubscriberByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DefaultLatitude,
		&i.DefaultLongitude,
		&i.DefaultRadiusMiles,
		&i.EmailUnsubscribeToken,
		&i.PreferredCategories,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, external_id, source, title, description, venue_name, address, city, state, zip, latitude, longitude, start_time, end_time, image_url, ticket_url, price_min, price_max, submitted_by, created_at, updated_at, manually_edited, venue_id, categories FROM events WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Source,
		&i.Title,
		&i.Description,
		&i.VenueName,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.StartTime,
		&i.EndTime,
		&i.ImageUrl,
		&i.TicketUrl,
		&i.PriceMin,
		&i.PriceMax,
		&i.SubmittedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ManuallyEdited,
		&i.VenueID,
		&i.Categories,
	)
	return i, err
}

const getEventSaveCount = `-- name: GetEventSaveCount :one
SELECT COUNT(*) FROM saved_events WHERE event_id = $1
`

func (q *Queries) GetEventSaveCount(ctx context.Context, eventID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getEventSaveCount, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getImage = `-- name: GetImage :one
SELECT id, user_id, r2_key, url, filename, content_type, size_bytes, created_at FROM images WHERE id = $1
`

func (q *Queries) GetImage(ctx context.Context, id pgtype.UUID) (Image, error) {
	row := q.db.QueryRow(ctx, getImage, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.R2Key,
		&i.Url,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const getLastNotificationSent = `-- name: GetLastNotificationSent :one
SELECT id, user_id, channel, sent_at, event_count, status, error_message FROM notification_log
WHERE user_id = $1 AND channel = $2 AND status = 'sent'
ORDER BY sent_at DESC
LIMIT 1
`

type GetLastNotificationSentParams struct {
	UserID  pgtype.UUID
	Channel string
}

func (q *Queries) GetLastNotificationSent(ctx context.Context, arg GetLastNotificationSentParams) (NotificationLog, error) {
	row := q.db.QueryRow(ctx, getLastNotificationSent, arg.UserID, arg.Channel)
	var i NotificationLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Channel,
		&i.SentAt,
		&i.EventCount,
		&i.Status,
		&i.ErrorMessage,
	)
	return i, err
}

const getNotificationPreferences = `-- name: GetNotificationPreferences :one
SELECT id, user_id, email_enabled, sms_enabled, email_unsubscribe_token, sms_unsubscribe_token, created_at, updated_at, preferred_categories FROM notification_preferences WHERE user_id = $1
`

func (q *Queries) GetNotificationPreferences(ctx context.Context, userID pgtype.UUID) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, getNotificationPreferences, userID)
	var i NotificationPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EmailEnabled,
		&i.SmsEnabled,
		&i.EmailUnsubscribeToken,
		&i.SmsUnsubscribeToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PreferredCategories,
	)
	return i, err
}

const getUserByClerkID = `-- name: GetUserByClerkID :one
SELECT id, clerk_id, username, email, default_latitude, default_longitude, default_radius_miles, created_at, updated_at, phone_number FROM users WHERE clerk_id = $1
`

func (q *Queries) GetUserByClerkID(ctx context.Context, clerkID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByClerkID, clerkID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Username,
		&i.Email,
		&i.DefaultLatitude,
		&i.DefaultLongitude,
		&i.DefaultRadiusMiles,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, clerk_id, username, email, default_latitude, default_longitude, default_radius_miles, created_at, updated_at, phone_number FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Username,
		&i.Email,
		&i.DefaultLatitude,
		&i.DefaultLongitude,
		&i.DefaultRadiusMiles,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
	)
	return i, err
}

const getUserCategoryAffinities = `-- name: GetUserCategoryAffinities :many
SELECT unnest(e.categories)::text AS category, COUNT(*) AS save_count
FROM saved_events se
JOIN events e ON e.id = se.event_id
WHERE se.user_id = $1
GROUP BY category
ORDER BY save_count DESC
LIMIT 10
`

type GetUserCategoryAffinitiesRow struct {
	Category  string
	SaveCount int64
}

func (q *Queries) GetUserCategoryAffinities(ctx context.Context, userID pgtype.UUID) ([]GetUserCategoryAffinitiesRow, error) {
	rows, err := q.db.Query(ctx, getUserCategoryAffinities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserCategoryAffinitiesRow
	for rows.Next() {
		var i GetUserCategoryAffinitiesRow
		if err := rows.Scan(&i.Category, &i.SaveCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVenue = `-- name: GetVenue :one
SELECT id, name, address, city, state, zip, latitude, longitude, hours, description, created_at, updated_at FROM venues WHERE id = $1
`

func (q *Queries) GetVenue(ctx context.Context, id pgtype.UUID) (Venue, error) {
	row := q.db.QueryRow(ctx, getVenue, id)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.Hours,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmailSubscribers = `-- name: ListEmailSubscribers :many
SELECT u.id, u.email, u.default_latitude, u.default_longitude, u.default_radius_miles,
       np.email_unsubscribe_token, np.preferred_categories
FROM users u
JOIN notification_preferences np ON np.user_id = u.id
WHERE np.email_enabled = TRUE
  AND u.email IS NOT NULL
  AND u.default_latitude IS NOT NULL
  AND u.default_longitude IS NOT NULL
`

type ListEmailSubscribersRow struct {
	ID                    pgtype.UUID
	Email                 pgtype.Text
	DefaultLatitude       pgtype.Float8
	DefaultLongitude      pgtype.Float8
	DefaultRadiusMiles    pgtype.Int4
	EmailUnsubscribeToken pgtype.UUID
	PreferredCategories   []string
}

func (q *Queries) ListEmailSubscribers(ctx context.Context) ([]ListEmailSubscribersRow, error) {
	rows, err := q.db.Query(ctx, listEmailSubscribers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmailSubscribersRow
	for rows.Next() {
		var i ListEmailSubscribersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DefaultLatitude,
			&i.DefaultLongitude,
			&i.DefaultRadiusMiles,
			&i.EmailUnsubscribeToken,
			&i.PreferredCategories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventIDsForSitemap = `-- name: ListEventIDsForSitemap :many
SELECT id, updated_at FROM events WHERE start_time >= NOW() ORDER BY start_time ASC
`

type ListEventIDsForSitemapRow struct {
	ID        pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListEventIDsForSitemap(ctx context.Context) ([]ListEventIDsForSitemapRow, error) {
	rows, err := q.db.Query(ctx, listEventIDsForSitemap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventIDsForSitemapRow
	for rows.Next() {
		var i ListEventIDsForSitemapRow
		if err := rows.Scan(&i.ID, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByLocation = `-- name: ListEventsByLocation :many
SELECT id, external_id, source, title, description, venue_name, address, city, state, zip, latitude, longitude, start_time, end_time, image_url, ticket_url, price_min, price_max, submitted_by, created_at, updated_at, manually_edited, venue_id, categories
FROM events
WHERE ST_DWithin(
    ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography,
    ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography,
    $3::float
)
AND start_time >= $4::timestamptz
AND start_time < $5::timestamptz
AND ($6::text IS NULL OR $6::text = ANY(categories))
AND ($7::text IS NULL OR venue_name = $7::text)
AND ($8::uuid IS NULL OR venue_id = $8::uuid)
AND ($9::text IS NULL OR title ILIKE '%' || $9::text || '%' OR venue_name ILIKE '%' || $9::text || '%')
ORDER BY ST_Distance(
    ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography,
    ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography
) ASC, start_time ASC
LIMIT $11 OFFSET $10
`

type ListEventsByLocationParams struct {
	Lng          float64
	Lat          float64
	RadiusMeters float64
	StartDate    pgtype.Timestamptz
	EndDate      pgtype.Timestamptz
	Category     pgtype.Text
	VenueName    pgtype.Text
	VenueID      pgtype.UUID
	Search       pgtype.Text
	EventOffset  int32
	EventLimit   int32
}

func (q *Queries) ListEventsByLocation(ctx context.Context, arg ListEventsByLocationParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByLocation,
		arg.Lng,
		arg.Lat,
		arg.RadiusMeters,
		arg.StartDate,
		arg.EndDate,
		arg.Category,
		arg.VenueName,
		arg.VenueID,
		arg.Search,
		arg.EventOffset,
		arg.EventLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Source,
			&i.Title,
			&i.Description,
			&i.VenueName,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Latitude,
			&i.Longitude,
			&i.StartTime,
			&i.EndTime,
			&i.ImageUrl,
			&i.TicketUrl,
			&i.PriceMin,
			&i.PriceMax,
			&i.SubmittedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ManuallyEdited,
			&i.VenueID,
			&i.Categories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByLocationDateSorted = `-- name: ListEventsByLocationDateSorted :many
SELECT id, external_id, source, title, description, venue_name, address, city, state, zip, latitude, longitude, start_time, end_time, image_url, ticket_url, price_min, price_max, submitted_by, created_at, updated_at, manually_edited, venue_id, categories
FROM events
WHERE ST_DWithin(
    ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography,
    ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography,
    $3::float
)
AND start_time >= $4::timestamptz
AND start_time < $5::timestamptz
AND ($6::text IS NULL OR $6::text = ANY(categories))
AND ($7::text IS NULL OR venue_name = $7::text)
AND ($8::uuid IS NULL OR venue_id = $8::uuid)
AND ($9::text IS NULL OR title ILIKE '%' || $9::text || '%' OR venue_name ILIKE '%' || $9::text || '%')
ORDER BY (start_time AT TIME ZONE 'America/New_York')::date ASC,
    ST_Distance(
        ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography,
        ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography
    ) ASC,
    start_time ASC
LIMIT $11 OFFSET $10
`

type ListEventsByLocationDateSortedParams struct {
	Lng          float64
	Lat          float64
	RadiusMeters float64
	StartDate    pgtype.Timestamptz
	EndDate      pgtype.Timestamptz
	Category     pgtype.Text
	VenueName    pgtype.Text
	VenueID      pgtype.UUID
	Search       pgtype.Text
	EventOffset  int32
	EventLimit   int32
}

func (q *Queries) ListEventsByLocationDateSorted(ctx context.Context, arg ListEventsByLocationDateSortedParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByLocationDateSorted,
		arg.Lng,
		arg.Lat,
		arg.RadiusMeters,
		arg.StartDate,
		arg.EndDate,
		arg.Category,
		arg.VenueName,
		arg.VenueID,
		arg.Search,
		arg.EventOffset,
		arg.EventLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Source,
			&i.Title,
			&i.Description,
			&i.VenueName,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Latitude,
			&i.Longitude,
			&i.StartTime,
			&i.EndTime,
			&i.ImageUrl,
			&i.TicketUrl,
			&i.PriceMin,
			&i.PriceMax,
			&i.SubmittedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ManuallyEdited,
			&i.VenueID,
			&i.Categories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsBySubmitter = `-- name: ListEventsBySubmitter :many
SELECT id, external_id, source, title, description, venue_name, address, city, state, zip, latitude, longitude, start_time, end_time, image_url, ticket_url, price_min, price_max, submitted_by, created_at, updated_at, manually_edited, venue_id, categories FROM events
WHERE submitted_by = $1
ORDER BY start_time ASC
`

func (q *Queries) ListEventsBySubmitter(ctx context.Context, submittedBy pgtype.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsBySubmitter, submittedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Source,
			&i.Title,
			&i.Description,
			&i.VenueName,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Latitude,
			&i.Longitude,
			&i.StartTime,
			&i.EndTime,
			&i.ImageUrl,
			&i.TicketUrl,
			&i.PriceMin,
			&i.PriceMax,
			&i.SubmittedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ManuallyEdited,
			&i.VenueID,
			&i.Categories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesByUser = `-- name: ListImagesByUser :many
SELECT id, user_id, r2_key, url, filename, content_type, size_bytes, created_at FROM images
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListImagesByUser(ctx context.Context, userID pgtype.UUID) ([]Image, error) {
	rows, err := q.db.Query(ctx, listImagesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.R2Key,
			&i.Url,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPastEventImageURLs = `-- name: ListPastEventImageURLs :many
SELECT DISTINCT image_url
FROM events
WHERE start_time < NOW()::date
  AND image_url IS NOT NULL
  AND image_url LIKE '%/events/%'
  AND image_url NOT IN (
      SELECT image_url FROM events
      WHERE start_time >= NOW()::date
        AND image_url IS NOT NULL
  )
`

func (q *Queries) ListPastEventImageURLs(ctx context.Context) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listPastEventImageURLs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var image_url pgtype.Text
		if err := rows.Scan(&image_url); err != nil {
			return nil, err
		}
		items = append(items, image_url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingApplications = `-- name: ListPendingApplications :many
SELECT id, clerk_id, full_name, email, bio, experience, status, submitted_at, reviewed_at, reviewed_by, review_notes FROM author_applications
WHERE status = 'pending'
ORDER BY submitted_at ASC
`

func (q *Queries) ListPendingApplications(ctx context.Context) ([]AuthorApplication, error) {
	rows, err := q.db.Query(ctx, listPendingApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthorApplication
	for rows.Next() {
		var i AuthorApplication
		if err := rows.Scan(
			&i.ID,
			&i.ClerkID,
			&i.FullName,
			&i.Email,
			&i.Bio,
			&i.Experience,
			&i.Status,
			&i.SubmittedAt,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.ReviewNotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingEditSuggestions = `-- name: ListPendingEditSuggestions :many
SELECT id, target_type, target_id, submitted_by, proposed_changes, status, review_notes, reviewed_by, created_at, reviewed_at FROM edit_suggestions
WHERE status = 'pending'
ORDER BY created_at ASC
`

func (q *Queries) ListPendingEditSuggestions(ctx context.Context) ([]EditSuggestion, error) {
	rows, err := q.db.Query(ctx, listPendingEditSuggestions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EditSuggestion
	for rows.Next() {
		var i EditSuggestion
		if err := rows.Scan(
			&i.ID,
			&i.TargetType,
			&i.TargetID,
			&i.SubmittedBy,
			&i.ProposedChanges,
			&i.Status,
			&i.ReviewNotes,
			&i.ReviewedBy,
			&i.CreatedAt,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingEditSuggestionsForAuthor = `-- name: ListPendingEditSuggestionsForAuthor :many
SELECT es.id, es.target_type, es.target_id, es.submitted_by, es.proposed_changes, es.status, es.review_notes, es.reviewed_by, es.created_at, es.reviewed_at FROM edit_suggestions es
JOIN events e ON es.target_type = 'event' AND es.target_id = e.id
JOIN users u ON e.submitted_by = u.id
WHERE u.clerk_id = $1 AND es.status = 'pending'
ORDER BY es.created_at ASC
`

func (q *Queries) ListPendingEditSuggestionsForAuthor(ctx context.Context, clerkID string) ([]EditSuggestion, error) {
	rows, err := q.db.Query(ctx, listPendingEditSuggestionsForAuthor, clerkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EditSuggestion
	for rows.Next() {
		var i EditSuggestion
		if err := rows.Scan(
			&i.ID,
			&i.TargetType,
			&i.TargetID,
			&i.SubmittedBy,
			&i.ProposedChanges,
			&i.Status,
			&i.ReviewNotes,
			&i.ReviewedBy,
			&i.CreatedAt,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingEditSuggestionsForTarget = `-- name: ListPendingEditSuggestionsForTarget :many
SELECT id, target_type, target_id, submitted_by, proposed_changes, status, review_notes, reviewed_by, created_at, reviewed_at FROM edit_suggestions
WHERE target_type = $1 AND target_id = $2 AND status = 'pending'
ORDER BY created_at ASC
`

type ListPendingEditSuggestionsForTargetParams struct {
	TargetType string
	TargetID   pgtype.UUID
}

func (q *Queries) ListPendingEditSuggestionsForTarget(ctx context.Context, arg ListPendingEditSuggestionsForTargetParams) ([]EditSuggestion, error) {
	rows, err := q.db.Query(ctx, listPendingEditSuggestionsForTarget, arg.TargetType, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EditSuggestion
	for rows.Next() {
		var i EditSuggestion
		if err := rows.Scan(
			&i.ID,
			&i.TargetType,
			&i.TargetID,
			&i.SubmittedBy,
			&i.ProposedChanges,
			&i.Status,
			&i.ReviewNotes,
			&i.ReviewedBy,
			&i.CreatedAt,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSMSSubscribers = `-- name: ListSMSSubscribers :many
SELECT u.id, u.clerk_id, u.phone_number, u.default_latitude, u.default_longitude, u.default_radius_miles,
       np.sms_unsubscribe_token, np.preferred_categories
FROM users u
JOIN notification_preferences np ON np.user_id = u.id
WHERE np.sms_enabled = TRUE
  AND u.phone_number IS NOT NULL
  AND u.default_latitude IS NOT NULL
  AND u.default_longitude IS NOT NULL
`

type ListSMSSubscribersRow struct {
	ID                  pgtype.UUID
	ClerkID             string
	PhoneNumber         pgtype.Text
	DefaultLatitude     pgtype.Float8
	DefaultLongitude    pgtype.Float8
	DefaultRadiusMiles  pgtype.Int4
	SmsUnsubscribeToken pgtype.UUID
	PreferredCategories []string
}

func (q *Queries) ListSMSSubscribers(ctx context.Context) ([]ListSMSSubscribersRow, error) {
	rows, err := q.db.Query(ctx, listSMSSubscribers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSMSSubscribersRow
	for rows.Next() {
		var i ListSMSSubscribersRow
		if err := rows.Scan(
			&i.ID,
			&i.ClerkID,
			&i.PhoneNumber,
			&i.DefaultLatitude,
			&i.DefaultLongitude,
			&i.DefaultRadiusMiles,
			&i.SmsUnsubscribeToken,
			&i.PreferredCategories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedEvents = `-- name: ListSavedEvents :many
SELECT e.id, e.external_id, e.source, e.title, e.description, e.venue_name, e.address, e.city, e.state, e.zip, e.latitude, e.longitude, e.start_time, e.end_time, e.image_url, e.ticket_url, e.price_min, e.price_max, e.submitted_by, e.created_at, e.updated_at, e.manually_edited, e.venue_id, e.categories
FROM events e
JOIN saved_events se ON se.event_id = e.id
WHERE se.user_id = $1
ORDER BY e.start_time ASC
`

func (q *Queries) ListSavedEvents(ctx context.Context, userID pgtype.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, listSavedEvents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Source,
			&i.Title,
			&i.Description,
			&i.VenueName,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Latitude,
			&i.Longitude,
			&i.StartTime,
			&i.EndTime,
			&i.ImageUrl,
			&i.TicketUrl,
			&i.PriceMin,
			&i.PriceMax,
			&i.SubmittedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ManuallyEdited,
			&i.VenueID,
			&i.Categories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedEventsForDigest = `-- name: ListSavedEventsForDigest :many
SELECT e.id, e.external_id, e.source, e.title, e.description, e.venue_name, e.address, e.city, e.state, e.zip, e.latitude, e.longitude, e.start_time, e.end_time, e.image_url, e.ticket_url, e.price_min, e.price_max, e.submitted_by, e.created_at, e.updated_at, e.manually_edited, e.venue_id, e.categories
FROM events e
JOIN saved_events se ON se.event_id = e.id
WHERE se.user_id = $1
  AND e.start_time >= $2::timestamptz
  AND e.start_time < $3::timestamptz
ORDER BY e.start_time ASC
`

type ListSavedEventsForDigestParams struct {
	UserID    pgtype.UUID
	StartDate pgtype.Timestamptz
	EndDate   pgtype.Timestamptz
}

func (q *Queries) ListSavedEventsForDigest(ctx context.Context, arg ListSavedEventsForDigestParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listSavedEventsForDigest, arg.UserID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Source,
			&i.Title,
			&i.Description,
			&i.VenueName,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Latitude,
			&i.Longitude,
			&i.StartTime,
			&i.EndTime,
			&i.ImageUrl,
			&i.TicketUrl,
			&i.PriceMin,
			&i.PriceMax,
			&i.SubmittedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ManuallyEdited,
			&i.VenueID,
			&i.Categories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingEventsForDigest = `-- name: ListUpcomingEventsForDigest :many
SELECT id, external_id, source, title, description, venue_name, address, city, state, zip, latitude, longitude, start_time, end_time, image_url, ticket_url, price_min, price_max, submitted_by, created_at, updated_at, manually_edited, venue_id, categories
FROM events
WHERE ST_DWithin(
    ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography,
    ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography,
    $3::float
)
AND start_time >= $4::timestamptz
AND start_time < $5::timestamptz
ORDER BY start_time ASC
LIMIT 50
`

type ListUpcomingEventsForDigestParams struct {
	Lng          float64
	Lat          float64
	RadiusMeters float64
	StartDate    pgtype.Timestamptz
	EndDate      pgtype.Timestamptz
}

func (q *Queries) ListUpcomingEventsForDigest(ctx context.Context, arg ListUpcomingEventsForDigestParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listUpcomingEventsForDigest,
		arg.Lng,
		arg.Lat,
		arg.RadiusMeters,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Source,
			&i.Title,
			&i.Description,
			&i.VenueName,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Latitude,
			&i.Longitude,
			&i.StartTime,
			&i.EndTime,
			&i.ImageUrl,
			&i.TicketUrl,
			&i.PriceMin,
			&i.PriceMax,
			&i.SubmittedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ManuallyEdited,
			&i.VenueID,
			&i.Categories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVenueIDsForSitemap = `-- name: ListVenueIDsForSitemap :many
SELECT id, updated_at FROM venues ORDER BY id ASC
`

type ListVenueIDsForSitemapRow struct {
	ID        pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListVenueIDsForSitemap(ctx context.Context) ([]ListVenueIDsForSitemapRow, error) {
	rows, err := q.db.Query(ctx, listVenueIDsForSitemap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVenueIDsForSitemapRow
	for rows.Next() {
		var i ListVenueIDsForSitemapRow
		if err := rows.Scan(&i.ID, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVenuesByLocation = `-- name: ListVenuesByLocation :many
SELECT id, name, address, city, state, zip, latitude, longitude, hours, description, created_at, updated_at
FROM venues
WHERE ST_DWithin(
    ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography,
    ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography,
    $3::float
)
ORDER BY name ASC
`

type ListVenuesByLocationParams struct {
	Lng          float64
	Lat          float64
	RadiusMeters float64
}

func (q *Queries) ListVenuesByLocation(ctx context.Context, arg ListVenuesByLocationParams) ([]Venue, error) {
	rows, err := q.db.Query(ctx, listVenuesByLocation, arg.Lng, arg.Lat, arg.RadiusMeters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Venue
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Latitude,
			&i.Longitude,
			&i.Hours,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectApplication = `-- name: RejectApplication :one
UPDATE author_applications SET
    status = 'rejected',
    reviewed_at = NOW(),
    reviewed_by = $2,
    review_notes = $3
WHERE id = $1
RETURNING id, clerk_id, full_name, email, bio, experience, status, submitted_at, reviewed_at, reviewed_by, review_notes
`

type RejectApplicationParams struct {
	ID          pgtype.UUID
	ReviewedBy  pgtype.Text
	ReviewNotes pgtype.Text
}

func (q *Queries) RejectApplication(ctx context.Context, arg RejectApplicationParams) (AuthorApplication, error) {
	row := q.db.QueryRow(ctx, rejectApplication, arg.ID, arg.ReviewedBy, arg.ReviewNotes)
	var i AuthorApplication
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.FullName,
		&i.Email,
		&i.Bio,
		&i.Experience,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.ReviewNotes,
	)
	return i, err
}

const rejectEditSuggestion = `-- name: RejectEditSuggestion :one
UPDATE edit_suggestions SET
    status = 'rejected',
    reviewed_at = NOW(),
    reviewed_by = $2,
    review_notes = $3
WHERE id = $1
RETURNING id, target_type, target_id, submitted_by, proposed_changes, status, review_notes, reviewed_by, created_at, reviewed_at
`

type RejectEditSuggestionParams struct {
	ID          pgtype.UUID
	ReviewedBy  pgtype.Text
	ReviewNotes pgtype.Text
}

func (q *Queries) RejectEditSuggestion(ctx context.Context, arg RejectEditSuggestionParams) (EditSuggestion, error) {
	row := q.db.QueryRow(ctx, rejectEditSuggestion, arg.ID, arg.ReviewedBy, arg.ReviewNotes)
	var i EditSuggestion
	err := row.Scan(
		&i.ID,
		&i.TargetType,
		&i.TargetID,
		&i.SubmittedBy,
		&i.ProposedChanges,
		&i.Status,
		&i.ReviewNotes,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.ReviewedAt,
	)
	return i, err
}

const resubscribeSMSByPhoneNumber = `-- name: ResubscribeSMSByPhoneNumber :exec
UPDATE notification_preferences SET sms_enabled = TRUE, updated_at = NOW()
WHERE user_id = (SELECT id FROM users WHERE phone_number = $1 LIMIT 1)
`

func (q *Queries) ResubscribeSMSByPhoneNumber(ctx context.Context, phoneNumber pgtype.Text) error {
	_, err := q.db.Exec(ctx, resubscribeSMSByPhoneNumber, phoneNumber)
	return err
}

const saveEvent = `-- name: SaveEvent :one
INSERT INTO saved_events (user_id, event_id)
VALUES ($1, $2)
ON CONFLICT (user_id, event_id) DO NOTHING
RETURNING id, user_id, event_id, created_at
`

type SaveEventParams struct {
	UserID  pgtype.UUID
	EventID pgtype.UUID
}

func (q *Queries) SaveEvent(ctx context.Context, arg SaveEventParams) (SavedEvent, error) {
	row := q.db.QueryRow(ctx, saveEvent, arg.UserID, arg.EventID)
	var i SavedEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.CreatedAt,
	)
	return i, err
}

const trackDeletedExternalEvent = `-- name: TrackDeletedExternalEvent :exec
INSERT INTO deleted_external_events (source, external_id)
VALUES ($1, $2)
ON CONFLICT (source, external_id) DO NOTHING
`

type TrackDeletedExternalEventParams struct {
	Source     string
	ExternalID string
}

func (q *Queries) TrackDeletedExternalEvent(ctx context.Context, arg TrackDeletedExternalEventParams) error {
	_, err := q.db.Exec(ctx, trackDeletedExternalEvent, arg.Source, arg.ExternalID)
	return err
}

const unsaveEvent = `-- name: UnsaveEvent :exec
DELETE FROM saved_events WHERE user_id = $1 AND event_id = $2
`

type UnsaveEventParams struct {
	UserID  pgtype.UUID
	EventID pgtype.UUID
}

func (q *Queries) UnsaveEvent(ctx context.Context, arg UnsaveEventParams) error {
	_, err := q.db.Exec(ctx, unsaveEvent, arg.UserID, arg.EventID)
	return err
}

const unsubscribeByEmailToken = `-- name: UnsubscribeByEmailToken :exec
UPDATE notification_preferences SET email_enabled = FALSE, updated_at = NOW()
WHERE email_unsubscribe_token = $1
`

func (q *Queries) UnsubscribeByEmailToken(ctx context.Context, emailUnsubscribeToken pgtype.UUID) error {
	_, err := q.db.Exec(ctx, unsubscribeByEmailToken, emailUnsubscribeToken)
	return err
}

const unsubscribeBySMSToken = `-- name: UnsubscribeBySMSToken :exec
UPDATE notification_preferences SET sms_enabled = FALSE, updated_at = NOW()
WHERE sms_unsubscribe_token = $1
`

func (q *Queries) UnsubscribeBySMSToken(ctx context.Context, smsUnsubscribeToken pgtype.UUID) error {
	_, err := q.db.Exec(ctx, unsubscribeBySMSToken, smsUnsubscribeToken)
	return err
}

const unsubscribeSMSByPhoneNumber = `-- name: UnsubscribeSMSByPhoneNumber :exec
UPDATE notification_preferences SET sms_enabled = FALSE, updated_at = NOW()
WHERE user_id = (SELECT id FROM users WHERE phone_number = $1 LIMIT 1)
`

func (q *Queries) UnsubscribeSMSByPhoneNumber(ctx context.Context, phoneNumber pgtype.Text) error {
	_, err := q.db.Exec(ctx, unsubscribeSMSByPhoneNumber, phoneNumber)
	return err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events SET
    title = $2,
    description = $3,
    venue_name = $4,
    address = $5,
    city = $6,
    state = $7,
    zip = $8,
    latitude = $9,
    longitude = $10,
    start_time = $11,
    end_time = $12,
    categories = $13,
    image_url = $14,
    ticket_url = $15,
    price_min = $16,
    price_max = $17,
    venue_id = $18,
    manually_edited = TRUE,
    updated_at = NOW()
WHERE id = $1
RETURNING id, external_id, source, title, description, venue_name, address, city, state, zip, latitude, longitude, start_time, end_time, image_url, ticket_url, price_min, price_max, submitted_by, created_at, updated_at, manually_edited, venue_id, categories
`

type UpdateEventParams struct {
	ID          pgtype.UUID
	Title       string
	Description pgtype.Text
	VenueName   pgtype.Text
	Address     pgtype.Text
	City        pgtype.Text
	State       pgtype.Text
	Zip         pgtype.Text
	Latitude    float64
	Longitude   float64
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	Categories  []string
	ImageUrl    pgtype.Text
	TicketUrl   pgtype.Text
	PriceMin    pgtype.Numeric
	PriceMax    pgtype.Numeric
	VenueID     pgtype.UUID
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.VenueName,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Latitude,
		arg.Longitude,
		arg.StartTime,
		arg.EndTime,
		arg.Categories,
		arg.ImageUrl,
		arg.TicketUrl,
		arg.PriceMin,
		arg.PriceMax,
		arg.VenueID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Source,
		&i.Title,
		&i.Description,
		&i.VenueName,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.StartTime,
		&i.EndTime,
		&i.ImageUrl,
		&i.TicketUrl,
		&i.PriceMin,
		&i.PriceMax,
		&i.SubmittedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ManuallyEdited,
		&i.VenueID,
		&i.Categories,
	)
	return i, err
}

const updateUserPhoneNumber = `-- name: UpdateUserPhoneNumber :exec
UPDATE users SET phone_number = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserPhoneNumberParams struct {
	ID          pgtype.UUID
	PhoneNumber pgtype.Text
}

func (q *Queries) UpdateUserPhoneNumber(ctx context.Context, arg UpdateUserPhoneNumberParams) error {
	_, err := q.db.Exec(ctx, updateUserPhoneNumber, arg.ID, arg.PhoneNumber)
	return err
}

const updateUserSettings = `-- name: UpdateUserSettings :one
UPDATE users SET
    default_latitude = $2,
    default_longitude = $3,
    default_radius_miles = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, clerk_id, username, email, default_latitude, default_longitude, default_radius_miles, created_at, updated_at, phone_number
`

type UpdateUserSettingsParams struct {
	ID                 pgtype.UUID
	DefaultLatitude    pgtype.Float8
	DefaultLongitude   pgtype.Float8
	DefaultRadiusMiles pgtype.Int4
}

func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserSettings,
		arg.ID,
		arg.DefaultLatitude,
		arg.DefaultLongitude,
		arg.DefaultRadiusMiles,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Username,
		&i.Email,
		&i.DefaultLatitude,
		&i.DefaultLongitude,
		&i.DefaultRadiusMiles,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
	)
	return i, err
}

const updateVenue = `-- name: UpdateVenue :one
UPDATE venues SET
    name = $2,
    address = $3,
    city = $4,
    state = $5,
    zip = $6,
    latitude = $7,
    longitude = $8,
    hours = $9,
    description = $10,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, address, city, state, zip, latitude, longitude, hours, description, created_at, updated_at
`

type UpdateVenueParams struct {
	ID          pgtype.UUID
	Name        string
	Address     pgtype.Text
	City        pgtype.Text
	State       pgtype.Text
	Zip         pgtype.Text
	Latitude    float64
	Longitude   float64
	Hours       pgtype.Text
	Description pgtype.Text
}

func (q *Queries) UpdateVenue(ctx context.Context, arg UpdateVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, updateVenue,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Latitude,
		arg.Longitude,
		arg.Hours,
		arg.Description,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.Hours,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertExternalEvent = `-- name: UpsertExternalEvent :one
INSERT INTO events (
    external_id, source, title, description, venue_name, address, city, state, zip,
    latitude, longitude, start_time, end_time, categories, image_url,
    ticket_url, price_min, price_max, venue_id
) SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19
WHERE NOT EXISTS (
    SELECT 1 FROM deleted_external_events d
    WHERE d.source = $2 AND d.external_id = $1
)
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL
DO UPDATE SET
    title=EXCLUDED.title, description=EXCLUDED.description,
    venue_name=EXCLUDED.venue_name, address=EXCLUDED.address,
    city=EXCLUDED.city, state=EXCLUDED.state, zip=EXCLUDED.zip,
    latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude,
    start_time=EXCLUDED.start_time, end_time=EXCLUDED.end_time,
    categories=EXCLUDED.categories, image_url=EXCLUDED.image_url,
    ticket_url=EXCLUDED.ticket_url, price_min=EXCLUDED.price_min,
    price_max=EXCLUDED.price_max, venue_id=EXCLUDED.venue_id, updated_at=NOW()
WHERE NOT events.manually_edited
RETURNING id, external_id, source, title, description, venue_name, address, city, state, zip, latitude, longitude, start_time, end_time, image_url, ticket_url, price_min, price_max, submitted_by, created_at, updated_at, manually_edited, venue_id, categories
`

type UpsertExternalEventParams struct {
	ExternalID  pgtype.Text
	Source      string
	Title       string
	Description pgtype.Text
	VenueName   pgtype.Text
	Address     pgtype.Text
	City        pgtype.Text
	State       pgtype.Text
	Zip         pgtype.Text
	Latitude    float64
	Longitude   float64
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	Categories  []string
	ImageUrl    pgtype.Text
	TicketUrl   pgtype.Text
	PriceMin    pgtype.Numeric
	PriceMax    pgtype.Numeric
	VenueID     pgtype.UUID
}

func (q *Queries) UpsertExternalEvent(ctx context.Context, arg UpsertExternalEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, upsertExternalEvent,
		arg.ExternalID,
		arg.Source,
		arg.Title,
		arg.Description,
		arg.VenueName,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Latitude,
		arg.Longitude,
		arg.StartTime,
		arg.EndTime,
		arg.Categories,
		arg.ImageUrl,
		arg.TicketUrl,
		arg.PriceMin,
		arg.PriceMax,
		arg.VenueID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Source,
		&i.Title,
		&i.Description,
		&i.VenueName,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.StartTime,
		&i.EndTime,
		&i.ImageUrl,
		&i.TicketUrl,
		&i.PriceMin,
		&i.PriceMax,
		&i.SubmittedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ManuallyEdited,
		&i.VenueID,
		&i.Categories,
	)
	return i, err
}

const upsertNotificationPreferences = `-- name: UpsertNotificationPreferences :one
INSERT INTO notification_preferences (user_id, email_enabled, sms_enabled, preferred_categories)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE SET
    email_enabled = EXCLUDED.email_enabled,
    sms_enabled = EXCLUDED.sms_enabled,
    preferred_categories = EXCLUDED.preferred_categories,
    updated_at = NOW()
RETURNING id, user_id, email_enabled, sms_enabled, email_unsubscribe_token, sms_unsubscribe_token, created_at, updated_at, preferred_categories
`

type UpsertNotificationPreferencesParams struct {
	UserID              pgtype.UUID
	EmailEnabled        bool
	SmsEnabled          bool
	PreferredCategories []string
}

func (q *Queries) UpsertNotificationPreferences(ctx context.Context, arg UpsertNotificationPreferencesParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertNotificationPreferences,
		arg.UserID,
		arg.EmailEnabled,
		arg.SmsEnabled,
		arg.PreferredCategories,
	)
	var i NotificationPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EmailEnabled,
		&i.SmsEnabled,
		&i.EmailUnsubscribeToken,
		&i.SmsUnsubscribeToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PreferredCategories,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (clerk_id, username, email)
VALUES ($1, $2, $3)
ON CONFLICT (clerk_id) DO UPDATE SET
    username = COALESCE(EXCLUDED.username, users.username),
    email = COALESCE(EXCLUDED.email, users.email),
    updated_at = NOW()
RETURNING id, clerk_id, username, email, default_latitude, default_longitude, default_radius_miles, created_at, updated_at, phone_number
`

type UpsertUserParams struct {
	ClerkID  string
	Username pgtype.Text
	Email    pgtype.Text
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.ClerkID, arg.Username, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Username,
		&i.Email,
		&i.DefaultLatitude,
		&i.DefaultLongitude,
		&i.DefaultRadiusMiles,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
	)
	return i, err
}

const upsertVenue = `-- name: UpsertVenue :one
INSERT INTO venues (name, address, city, state, zip, latitude, longitude)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (LOWER(TRIM(name)), COALESCE(NULLIF(LOWER(TRIM(address)), ''), latitude::text || ',' || longitude::text))
DO UPDATE SET
    address = COALESCE(NULLIF(EXCLUDED.address, ''), venues.address),
    city = COALESCE(NULLIF(EXCLUDED.city, ''), venues.city),
    state = COALESCE(NULLIF(EXCLUDED.state, ''), venues.state),
    zip = COALESCE(NULLIF(EXCLUDED.zip, ''), venues.zip),
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    updated_at = NOW()
RETURNING id, name, address, city, state, zip, latitude, longitude, hours, description, created_at, updated_at
`

type UpsertVenueParams struct {
	Name      string
	Address   pgtype.Text
	City      pgtype.Text
	State     pgtype.Text
	Zip       pgtype.Text
	Latitude  float64
	Longitude float64
}

func (q *Queries) UpsertVenue(ctx context.Context, arg UpsertVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, upsertVenue,
		arg.Name,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Latitude,
		arg.Longitude,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.Hours,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
