// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recommendations.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureUserPreferences = `-- name: EnsureUserPreferences :exec
INSERT INTO user_preferences (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO NOTHING
`

func (q *Queries) EnsureUserPreferences(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, ensureUserPreferences, userID)
	return err
}

const getUserPreferencesState = `-- name: GetUserPreferencesState :one
SELECT
    ((SELECT COUNT(*) FROM saved_events se WHERE se.user_id = $1)
        + (SELECT COUNT(*) FROM event_views ev WHERE ev.user_id = $1))::int AS signal_count,
    up.needs_recompute,
    (up.preference_vector IS NOT NULL)::bool AS has_vector
FROM user_preferences up
WHERE up.user_id = $1
`

type GetUserPreferencesStateRow struct {
	SignalCount    int32
	NeedsRecompute bool
	HasVector      bool
}

// signal_count is derived live so it cannot drift from saved_events/event_views.
// The stored column on user_preferences is no longer read.
func (q *Queries) GetUserPreferencesState(ctx context.Context, userID pgtype.UUID) (GetUserPreferencesStateRow, error) {
	row := q.db.QueryRow(ctx, getUserPreferencesState, userID)
	var i GetUserPreferencesStateRow
	err := row.Scan(&i.SignalCount, &i.NeedsRecompute, &i.HasVector)
	return i, err
}

const listTrendingFutureEvents = `-- name: ListTrendingFutureEvents :many
SELECT e.id, e.external_id, e.source, e.title, e.description, e.venue_name, e.address, e.city, e.state, e.zip, e.latitude, e.longitude, e.start_time, e.end_time, e.image_url, e.ticket_url, e.price_min, e.price_max, e.submitted_by, e.created_at, e.updated_at, e.manually_edited, e.venue_id, e.categories, e.series_id, e.is_free, e.is_featured, e.featured_at, e.featured_by, COUNT(se.user_id) AS save_count
FROM events e
LEFT JOIN saved_events se ON se.event_id = e.id
WHERE e.start_time > NOW()
  AND ST_DWithin(
      ST_SetSRID(ST_MakePoint(e.longitude, e.latitude), 4326)::geography,
      ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography,
      $3::float
  )
GROUP BY e.id
ORDER BY save_count DESC, e.start_time ASC
LIMIT $4
`

type ListTrendingFutureEventsParams struct {
	Lng          float64
	Lat          float64
	RadiusMeters float64
	EventLimit   int32
}

type ListTrendingFutureEventsRow struct {
	ID             pgtype.UUID
	ExternalID     pgtype.Text
	Source         string
	Title          string
	Description    pgtype.Text
	VenueName      pgtype.Text
	Address        pgtype.Text
	City           pgtype.Text
	State          pgtype.Text
	Zip            pgtype.Text
	Latitude       float64
	Longitude      float64
	StartTime      pgtype.Timestamptz
	EndTime        pgtype.Timestamptz
	ImageUrl       pgtype.Text
	TicketUrl      pgtype.Text
	PriceMin       pgtype.Numeric
	PriceMax       pgtype.Numeric
	SubmittedBy    pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ManuallyEdited bool
	VenueID        pgtype.UUID
	Categories     []string
	SeriesID       pgtype.UUID
	IsFree         bool
	IsFeatured     bool
	FeaturedAt     pgtype.Timestamptz
	FeaturedBy     pgtype.UUID
	SaveCount      int64
}

func (q *Queries) ListTrendingFutureEvents(ctx context.Context, arg ListTrendingFutureEventsParams) ([]ListTrendingFutureEventsRow, error) {
	rows, err := q.db.Query(ctx, listTrendingFutureEvents,
		arg.Lng,
		arg.Lat,
		arg.RadiusMeters,
		arg.EventLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrendingFutureEventsRow
	for rows.Next() {
		var i ListTrendingFutureEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Source,
			&i.Title,
			&i.Description,
			&i.VenueName,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Latitude,
			&i.Longitude,
			&i.StartTime,
			&i.EndTime,
			&i.ImageUrl,
			&i.TicketUrl,
			&i.PriceMin,
			&i.PriceMax,
			&i.SubmittedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ManuallyEdited,
			&i.VenueID,
			&i.Categories,
			&i.SeriesID,
			&i.IsFree,
			&i.IsFeatured,
			&i.FeaturedAt,
			&i.FeaturedBy,
			&i.SaveCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserPreferencesStale = `-- name: MarkUserPreferencesStale :exec
UPDATE user_preferences
SET needs_recompute = TRUE
WHERE user_id = $1
`

func (q *Queries) MarkUserPreferencesStale(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markUserPreferencesStale, userID)
	return err
}

const recordEventView = `-- name: RecordEventView :exec
INSERT INTO event_views (user_id, event_id, viewed_at)
VALUES ($1, $2, NOW())
ON CONFLICT (user_id, event_id) DO UPDATE SET viewed_at = NOW()
`

type RecordEventViewParams struct {
	UserID  pgtype.UUID
	EventID pgtype.UUID
}

func (q *Queries) RecordEventView(ctx context.Context, arg RecordEventViewParams) error {
	_, err := q.db.Exec(ctx, recordEventView, arg.UserID, arg.EventID)
	return err
}
