// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: saved_events.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEventSaveCount = `-- name: GetEventSaveCount :one
SELECT COUNT(*) FROM saved_events WHERE event_id = $1
`

func (q *Queries) GetEventSaveCount(ctx context.Context, eventID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getEventSaveCount, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserCategoryAffinities = `-- name: GetUserCategoryAffinities :many
SELECT unnest(e.categories)::text AS category, COUNT(*) AS save_count
FROM saved_events se
JOIN events e ON e.id = se.event_id
WHERE se.user_id = $1
GROUP BY category
ORDER BY save_count DESC
LIMIT 10
`

type GetUserCategoryAffinitiesRow struct {
	Category  string
	SaveCount int64
}

func (q *Queries) GetUserCategoryAffinities(ctx context.Context, userID pgtype.UUID) ([]GetUserCategoryAffinitiesRow, error) {
	rows, err := q.db.Query(ctx, getUserCategoryAffinities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserCategoryAffinitiesRow
	for rows.Next() {
		var i GetUserCategoryAffinitiesRow
		if err := rows.Scan(&i.Category, &i.SaveCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedEvents = `-- name: ListSavedEvents :many
SELECT e.id, e.external_id, e.source, e.title, e.description, e.venue_name, e.address, e.city, e.state, e.zip, e.latitude, e.longitude, e.start_time, e.end_time, e.image_url, e.ticket_url, e.price_min, e.price_max, e.submitted_by, e.created_at, e.updated_at, e.manually_edited, e.venue_id, e.categories, e.series_id, e.is_free
FROM events e
JOIN saved_events se ON se.event_id = e.id
WHERE se.user_id = $1
ORDER BY e.start_time ASC
`

func (q *Queries) ListSavedEvents(ctx context.Context, userID pgtype.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, listSavedEvents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Source,
			&i.Title,
			&i.Description,
			&i.VenueName,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Latitude,
			&i.Longitude,
			&i.StartTime,
			&i.EndTime,
			&i.ImageUrl,
			&i.TicketUrl,
			&i.PriceMin,
			&i.PriceMax,
			&i.SubmittedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ManuallyEdited,
			&i.VenueID,
			&i.Categories,
			&i.SeriesID,
			&i.IsFree,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedEventsForDigest = `-- name: ListSavedEventsForDigest :many
SELECT e.id, e.external_id, e.source, e.title, e.description, e.venue_name, e.address, e.city, e.state, e.zip, e.latitude, e.longitude, e.start_time, e.end_time, e.image_url, e.ticket_url, e.price_min, e.price_max, e.submitted_by, e.created_at, e.updated_at, e.manually_edited, e.venue_id, e.categories, e.series_id, e.is_free
FROM events e
JOIN saved_events se ON se.event_id = e.id
WHERE se.user_id = $1
  AND e.start_time >= $2::timestamptz
  AND e.start_time < $3::timestamptz
ORDER BY e.start_time ASC
`

type ListSavedEventsForDigestParams struct {
	UserID    pgtype.UUID
	StartDate pgtype.Timestamptz
	EndDate   pgtype.Timestamptz
}

func (q *Queries) ListSavedEventsForDigest(ctx context.Context, arg ListSavedEventsForDigestParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listSavedEventsForDigest, arg.UserID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Source,
			&i.Title,
			&i.Description,
			&i.VenueName,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Latitude,
			&i.Longitude,
			&i.StartTime,
			&i.EndTime,
			&i.ImageUrl,
			&i.TicketUrl,
			&i.PriceMin,
			&i.PriceMax,
			&i.SubmittedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ManuallyEdited,
			&i.VenueID,
			&i.Categories,
			&i.SeriesID,
			&i.IsFree,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveEvent = `-- name: SaveEvent :one
INSERT INTO saved_events (user_id, event_id)
VALUES ($1, $2)
ON CONFLICT (user_id, event_id) DO NOTHING
RETURNING id, user_id, event_id, created_at
`

type SaveEventParams struct {
	UserID  pgtype.UUID
	EventID pgtype.UUID
}

func (q *Queries) SaveEvent(ctx context.Context, arg SaveEventParams) (SavedEvent, error) {
	row := q.db.QueryRow(ctx, saveEvent, arg.UserID, arg.EventID)
	var i SavedEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.CreatedAt,
	)
	return i, err
}

const unsaveEvent = `-- name: UnsaveEvent :exec
DELETE FROM saved_events WHERE user_id = $1 AND event_id = $2
`

type UnsaveEventParams struct {
	UserID  pgtype.UUID
	EventID pgtype.UUID
}

func (q *Queries) UnsaveEvent(ctx context.Context, arg UnsaveEventParams) error {
	_, err := q.db.Exec(ctx, unsaveEvent, arg.UserID, arg.EventID)
	return err
}
