// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sitemap.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listEventIDsForSitemap = `-- name: ListEventIDsForSitemap :many
SELECT id, updated_at FROM events WHERE start_time >= NOW() ORDER BY start_time ASC
`

type ListEventIDsForSitemapRow struct {
	ID        pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListEventIDsForSitemap(ctx context.Context) ([]ListEventIDsForSitemapRow, error) {
	rows, err := q.db.Query(ctx, listEventIDsForSitemap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventIDsForSitemapRow
	for rows.Next() {
		var i ListEventIDsForSitemapRow
		if err := rows.Scan(&i.ID, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVenueIDsForSitemap = `-- name: ListVenueIDsForSitemap :many
SELECT id, updated_at FROM venues ORDER BY id ASC
`

type ListVenueIDsForSitemapRow struct {
	ID        pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListVenueIDsForSitemap(ctx context.Context) ([]ListVenueIDsForSitemapRow, error) {
	rows, err := q.db.Query(ctx, listVenueIDsForSitemap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVenueIDsForSitemapRow
	for rows.Next() {
		var i ListVenueIDsForSitemapRow
		if err := rows.Scan(&i.ID, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
