// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscribers.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmEmailSubscriber = `-- name: ConfirmEmailSubscriber :one
UPDATE email_digest_subscribers
SET confirmed = TRUE, confirmed_at = NOW()
WHERE confirm_token = $1
RETURNING id, email, latitude, longitude, radius_miles, preferred_categories, digest_format, email_style, confirmed, confirm_token, unsubscribe_token, last_sent_at, created_at, confirmed_at
`

func (q *Queries) ConfirmEmailSubscriber(ctx context.Context, confirmToken pgtype.UUID) (EmailDigestSubscriber, error) {
	row := q.db.QueryRow(ctx, confirmEmailSubscriber, confirmToken)
	var i EmailDigestSubscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Latitude,
		&i.Longitude,
		&i.RadiusMiles,
		&i.PreferredCategories,
		&i.DigestFormat,
		&i.EmailStyle,
		&i.Confirmed,
		&i.ConfirmToken,
		&i.UnsubscribeToken,
		&i.LastSentAt,
		&i.CreatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const listConfirmedAnonymousSubscribers = `-- name: ListConfirmedAnonymousSubscribers :many
SELECT id, email, latitude, longitude, radius_miles, preferred_categories, digest_format, email_style, confirmed, confirm_token, unsubscribe_token, last_sent_at, created_at, confirmed_at FROM email_digest_subscribers
WHERE confirmed = TRUE
`

func (q *Queries) ListConfirmedAnonymousSubscribers(ctx context.Context) ([]EmailDigestSubscriber, error) {
	rows, err := q.db.Query(ctx, listConfirmedAnonymousSubscribers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailDigestSubscriber
	for rows.Next() {
		var i EmailDigestSubscriber
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Latitude,
			&i.Longitude,
			&i.RadiusMiles,
			&i.PreferredCategories,
			&i.DigestFormat,
			&i.EmailStyle,
			&i.Confirmed,
			&i.ConfirmToken,
			&i.UnsubscribeToken,
			&i.LastSentAt,
			&i.CreatedAt,
			&i.ConfirmedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAnonymousSubscriberSent = `-- name: MarkAnonymousSubscriberSent :exec
UPDATE email_digest_subscribers SET last_sent_at = NOW() WHERE id = $1
`

func (q *Queries) MarkAnonymousSubscriberSent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAnonymousSubscriberSent, id)
	return err
}

const unsubscribeAnonymousByToken = `-- name: UnsubscribeAnonymousByToken :exec
DELETE FROM email_digest_subscribers WHERE unsubscribe_token = $1
`

func (q *Queries) UnsubscribeAnonymousByToken(ctx context.Context, unsubscribeToken pgtype.UUID) error {
	_, err := q.db.Exec(ctx, unsubscribeAnonymousByToken, unsubscribeToken)
	return err
}

const upsertEmailSubscriber = `-- name: UpsertEmailSubscriber :one
INSERT INTO email_digest_subscribers (email, latitude, longitude, radius_miles)
VALUES ($1, $2, $3, $4)
ON CONFLICT (email) DO UPDATE SET
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    radius_miles = EXCLUDED.radius_miles
RETURNING id, email, latitude, longitude, radius_miles, preferred_categories, digest_format, email_style, confirmed, confirm_token, unsubscribe_token, last_sent_at, created_at, confirmed_at
`

type UpsertEmailSubscriberParams struct {
	Email       string
	Latitude    float64
	Longitude   float64
	RadiusMiles int32
}

// Create a pending (unconfirmed) anonymous subscriber, or refresh the location
// of an existing one. Idempotent: re-subscribing an already-confirmed email just
// updates its location and leaves it confirmed (the handler skips resending the
// confirmation email in that case). The confirm/unsubscribe tokens are minted
// once at insert and preserved across updates.
func (q *Queries) UpsertEmailSubscriber(ctx context.Context, arg UpsertEmailSubscriberParams) (EmailDigestSubscriber, error) {
	row := q.db.QueryRow(ctx, upsertEmailSubscriber,
		arg.Email,
		arg.Latitude,
		arg.Longitude,
		arg.RadiusMiles,
	)
	var i EmailDigestSubscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Latitude,
		&i.Longitude,
		&i.RadiusMiles,
		&i.PreferredCategories,
		&i.DigestFormat,
		&i.EmailStyle,
		&i.Confirmed,
		&i.ConfirmToken,
		&i.UnsubscribeToken,
		&i.LastSentAt,
		&i.CreatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}
