// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: suggestions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveEditSuggestion = `-- name: ApproveEditSuggestion :one
UPDATE edit_suggestions SET
    status = 'approved',
    reviewed_at = NOW(),
    reviewed_by = $2,
    review_notes = $3
WHERE id = $1
RETURNING id, target_type, target_id, submitted_by, proposed_changes, status, review_notes, reviewed_by, created_at, reviewed_at, action, reason
`

type ApproveEditSuggestionParams struct {
	ID          pgtype.UUID
	ReviewedBy  pgtype.Text
	ReviewNotes pgtype.Text
}

func (q *Queries) ApproveEditSuggestion(ctx context.Context, arg ApproveEditSuggestionParams) (EditSuggestion, error) {
	row := q.db.QueryRow(ctx, approveEditSuggestion, arg.ID, arg.ReviewedBy, arg.ReviewNotes)
	var i EditSuggestion
	err := row.Scan(
		&i.ID,
		&i.TargetType,
		&i.TargetID,
		&i.SubmittedBy,
		&i.ProposedChanges,
		&i.Status,
		&i.ReviewNotes,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.ReviewedAt,
		&i.Action,
		&i.Reason,
	)
	return i, err
}

const createEditSuggestion = `-- name: CreateEditSuggestion :one
INSERT INTO edit_suggestions (target_type, target_id, submitted_by, proposed_changes, action, reason)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, target_type, target_id, submitted_by, proposed_changes, status, review_notes, reviewed_by, created_at, reviewed_at, action, reason
`

type CreateEditSuggestionParams struct {
	TargetType      string
	TargetID        pgtype.UUID
	SubmittedBy     pgtype.UUID
	ProposedChanges []byte
	Action          string
	Reason          pgtype.Text
}

func (q *Queries) CreateEditSuggestion(ctx context.Context, arg CreateEditSuggestionParams) (EditSuggestion, error) {
	row := q.db.QueryRow(ctx, createEditSuggestion,
		arg.TargetType,
		arg.TargetID,
		arg.SubmittedBy,
		arg.ProposedChanges,
		arg.Action,
		arg.Reason,
	)
	var i EditSuggestion
	err := row.Scan(
		&i.ID,
		&i.TargetType,
		&i.TargetID,
		&i.SubmittedBy,
		&i.ProposedChanges,
		&i.Status,
		&i.ReviewNotes,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.ReviewedAt,
		&i.Action,
		&i.Reason,
	)
	return i, err
}

const getEditSuggestion = `-- name: GetEditSuggestion :one
SELECT id, target_type, target_id, submitted_by, proposed_changes, status, review_notes, reviewed_by, created_at, reviewed_at, action, reason FROM edit_suggestions WHERE id = $1
`

func (q *Queries) GetEditSuggestion(ctx context.Context, id pgtype.UUID) (EditSuggestion, error) {
	row := q.db.QueryRow(ctx, getEditSuggestion, id)
	var i EditSuggestion
	err := row.Scan(
		&i.ID,
		&i.TargetType,
		&i.TargetID,
		&i.SubmittedBy,
		&i.ProposedChanges,
		&i.Status,
		&i.ReviewNotes,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.ReviewedAt,
		&i.Action,
		&i.Reason,
	)
	return i, err
}

const listPendingEditSuggestions = `-- name: ListPendingEditSuggestions :many
SELECT id, target_type, target_id, submitted_by, proposed_changes, status, review_notes, reviewed_by, created_at, reviewed_at, action, reason FROM edit_suggestions
WHERE status = 'pending'
ORDER BY created_at ASC
`

func (q *Queries) ListPendingEditSuggestions(ctx context.Context) ([]EditSuggestion, error) {
	rows, err := q.db.Query(ctx, listPendingEditSuggestions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EditSuggestion
	for rows.Next() {
		var i EditSuggestion
		if err := rows.Scan(
			&i.ID,
			&i.TargetType,
			&i.TargetID,
			&i.SubmittedBy,
			&i.ProposedChanges,
			&i.Status,
			&i.ReviewNotes,
			&i.ReviewedBy,
			&i.CreatedAt,
			&i.ReviewedAt,
			&i.Action,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingEditSuggestionsForAuthor = `-- name: ListPendingEditSuggestionsForAuthor :many
SELECT es.id, es.target_type, es.target_id, es.submitted_by, es.proposed_changes, es.status, es.review_notes, es.reviewed_by, es.created_at, es.reviewed_at, es.action, es.reason FROM edit_suggestions es
JOIN events e ON es.target_type = 'event' AND es.target_id = e.id
JOIN users u ON e.submitted_by = u.id
WHERE u.clerk_id = $1 AND es.status = 'pending'
ORDER BY es.created_at ASC
`

func (q *Queries) ListPendingEditSuggestionsForAuthor(ctx context.Context, clerkID string) ([]EditSuggestion, error) {
	rows, err := q.db.Query(ctx, listPendingEditSuggestionsForAuthor, clerkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EditSuggestion
	for rows.Next() {
		var i EditSuggestion
		if err := rows.Scan(
			&i.ID,
			&i.TargetType,
			&i.TargetID,
			&i.SubmittedBy,
			&i.ProposedChanges,
			&i.Status,
			&i.ReviewNotes,
			&i.ReviewedBy,
			&i.CreatedAt,
			&i.ReviewedAt,
			&i.Action,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingEditSuggestionsForTarget = `-- name: ListPendingEditSuggestionsForTarget :many
SELECT id, target_type, target_id, submitted_by, proposed_changes, status, review_notes, reviewed_by, created_at, reviewed_at, action, reason FROM edit_suggestions
WHERE target_type = $1 AND target_id = $2 AND status = 'pending'
ORDER BY created_at ASC
`

type ListPendingEditSuggestionsForTargetParams struct {
	TargetType string
	TargetID   pgtype.UUID
}

func (q *Queries) ListPendingEditSuggestionsForTarget(ctx context.Context, arg ListPendingEditSuggestionsForTargetParams) ([]EditSuggestion, error) {
	rows, err := q.db.Query(ctx, listPendingEditSuggestionsForTarget, arg.TargetType, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EditSuggestion
	for rows.Next() {
		var i EditSuggestion
		if err := rows.Scan(
			&i.ID,
			&i.TargetType,
			&i.TargetID,
			&i.SubmittedBy,
			&i.ProposedChanges,
			&i.Status,
			&i.ReviewNotes,
			&i.ReviewedBy,
			&i.CreatedAt,
			&i.ReviewedAt,
			&i.Action,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectEditSuggestion = `-- name: RejectEditSuggestion :one
UPDATE edit_suggestions SET
    status = 'rejected',
    reviewed_at = NOW(),
    reviewed_by = $2,
    review_notes = $3
WHERE id = $1
RETURNING id, target_type, target_id, submitted_by, proposed_changes, status, review_notes, reviewed_by, created_at, reviewed_at, action, reason
`

type RejectEditSuggestionParams struct {
	ID          pgtype.UUID
	ReviewedBy  pgtype.Text
	ReviewNotes pgtype.Text
}

func (q *Queries) RejectEditSuggestion(ctx context.Context, arg RejectEditSuggestionParams) (EditSuggestion, error) {
	row := q.db.QueryRow(ctx, rejectEditSuggestion, arg.ID, arg.ReviewedBy, arg.ReviewNotes)
	var i EditSuggestion
	err := row.Scan(
		&i.ID,
		&i.TargetType,
		&i.TargetID,
		&i.SubmittedBy,
		&i.ProposedChanges,
		&i.Status,
		&i.ReviewNotes,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.ReviewedAt,
		&i.Action,
		&i.Reason,
	)
	return i, err
}
