// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByClerkID = `-- name: GetUserByClerkID :one
SELECT id, clerk_id, username, email, default_latitude, default_longitude, default_radius_miles, created_at, updated_at, phone_number FROM users WHERE clerk_id = $1
`

func (q *Queries) GetUserByClerkID(ctx context.Context, clerkID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByClerkID, clerkID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Username,
		&i.Email,
		&i.DefaultLatitude,
		&i.DefaultLongitude,
		&i.DefaultRadiusMiles,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, clerk_id, username, email, default_latitude, default_longitude, default_radius_miles, created_at, updated_at, phone_number FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Username,
		&i.Email,
		&i.DefaultLatitude,
		&i.DefaultLongitude,
		&i.DefaultRadiusMiles,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
	)
	return i, err
}

const updateUserPhoneNumber = `-- name: UpdateUserPhoneNumber :exec
UPDATE users SET phone_number = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserPhoneNumberParams struct {
	ID          pgtype.UUID
	PhoneNumber pgtype.Text
}

func (q *Queries) UpdateUserPhoneNumber(ctx context.Context, arg UpdateUserPhoneNumberParams) error {
	_, err := q.db.Exec(ctx, updateUserPhoneNumber, arg.ID, arg.PhoneNumber)
	return err
}

const updateUserSettings = `-- name: UpdateUserSettings :one
UPDATE users SET
    default_latitude = $2,
    default_longitude = $3,
    default_radius_miles = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, clerk_id, username, email, default_latitude, default_longitude, default_radius_miles, created_at, updated_at, phone_number
`

type UpdateUserSettingsParams struct {
	ID                 pgtype.UUID
	DefaultLatitude    pgtype.Float8
	DefaultLongitude   pgtype.Float8
	DefaultRadiusMiles pgtype.Int4
}

func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserSettings,
		arg.ID,
		arg.DefaultLatitude,
		arg.DefaultLongitude,
		arg.DefaultRadiusMiles,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Username,
		&i.Email,
		&i.DefaultLatitude,
		&i.DefaultLongitude,
		&i.DefaultRadiusMiles,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (clerk_id, username, email)
VALUES ($1, $2, $3)
ON CONFLICT (clerk_id) DO UPDATE SET
    username = COALESCE(EXCLUDED.username, users.username),
    email = COALESCE(EXCLUDED.email, users.email),
    updated_at = NOW()
RETURNING id, clerk_id, username, email, default_latitude, default_longitude, default_radius_miles, created_at, updated_at, phone_number
`

type UpsertUserParams struct {
	ClerkID  string
	Username pgtype.Text
	Email    pgtype.Text
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.ClerkID, arg.Username, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Username,
		&i.Email,
		&i.DefaultLatitude,
		&i.DefaultLongitude,
		&i.DefaultRadiusMiles,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
	)
	return i, err
}
