// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: venue_claims.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveVenueClaim = `-- name: ApproveVenueClaim :one
UPDATE venue_claims SET
    status = 'approved',
    venue_id = COALESCE($2, venue_id),
    reviewed_at = NOW(),
    reviewed_by = $3,
    review_notes = $4
WHERE id = $1
RETURNING id, clerk_id, venue_id, venue_name, address, city, state, zip, latitude, longitude, contact_name, contact_email, booking_email, message, status, submitted_at, reviewed_at, reviewed_by, review_notes
`

type ApproveVenueClaimParams struct {
	ID          pgtype.UUID
	VenueID     pgtype.UUID
	ReviewedBy  pgtype.Text
	ReviewNotes pgtype.Text
}

func (q *Queries) ApproveVenueClaim(ctx context.Context, arg ApproveVenueClaimParams) (VenueClaim, error) {
	row := q.db.QueryRow(ctx, approveVenueClaim,
		arg.ID,
		arg.VenueID,
		arg.ReviewedBy,
		arg.ReviewNotes,
	)
	var i VenueClaim
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.VenueID,
		&i.VenueName,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.ContactName,
		&i.ContactEmail,
		&i.BookingEmail,
		&i.Message,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.ReviewNotes,
	)
	return i, err
}

const createVenueClaim = `-- name: CreateVenueClaim :one
INSERT INTO venue_claims (
    clerk_id, venue_id, venue_name, address, city, state, zip, latitude, longitude,
    contact_name, contact_email, booking_email, message
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, clerk_id, venue_id, venue_name, address, city, state, zip, latitude, longitude, contact_name, contact_email, booking_email, message, status, submitted_at, reviewed_at, reviewed_by, review_notes
`

type CreateVenueClaimParams struct {
	ClerkID      string
	VenueID      pgtype.UUID
	VenueName    string
	Address      pgtype.Text
	City         pgtype.Text
	State        pgtype.Text
	Zip          pgtype.Text
	Latitude     pgtype.Float8
	Longitude    pgtype.Float8
	ContactName  string
	ContactEmail string
	BookingEmail pgtype.Text
	Message      pgtype.Text
}

func (q *Queries) CreateVenueClaim(ctx context.Context, arg CreateVenueClaimParams) (VenueClaim, error) {
	row := q.db.QueryRow(ctx, createVenueClaim,
		arg.ClerkID,
		arg.VenueID,
		arg.VenueName,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Latitude,
		arg.Longitude,
		arg.ContactName,
		arg.ContactEmail,
		arg.BookingEmail,
		arg.Message,
	)
	var i VenueClaim
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.VenueID,
		&i.VenueName,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.ContactName,
		&i.ContactEmail,
		&i.BookingEmail,
		&i.Message,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.ReviewNotes,
	)
	return i, err
}

const getPendingVenueClaimForVenue = `-- name: GetPendingVenueClaimForVenue :one
SELECT id, clerk_id, venue_id, venue_name, address, city, state, zip, latitude, longitude, contact_name, contact_email, booking_email, message, status, submitted_at, reviewed_at, reviewed_by, review_notes FROM venue_claims
WHERE venue_id = $1 AND status = 'pending'
LIMIT 1
`

// Used to block duplicate pending claims on the same existing venue.
func (q *Queries) GetPendingVenueClaimForVenue(ctx context.Context, venueID pgtype.UUID) (VenueClaim, error) {
	row := q.db.QueryRow(ctx, getPendingVenueClaimForVenue, venueID)
	var i VenueClaim
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.VenueID,
		&i.VenueName,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.ContactName,
		&i.ContactEmail,
		&i.BookingEmail,
		&i.Message,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.ReviewNotes,
	)
	return i, err
}

const getVenueClaim = `-- name: GetVenueClaim :one
SELECT id, clerk_id, venue_id, venue_name, address, city, state, zip, latitude, longitude, contact_name, contact_email, booking_email, message, status, submitted_at, reviewed_at, reviewed_by, review_notes FROM venue_claims WHERE id = $1
`

func (q *Queries) GetVenueClaim(ctx context.Context, id pgtype.UUID) (VenueClaim, error) {
	row := q.db.QueryRow(ctx, getVenueClaim, id)
	var i VenueClaim
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.VenueID,
		&i.VenueName,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.ContactName,
		&i.ContactEmail,
		&i.BookingEmail,
		&i.Message,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.ReviewNotes,
	)
	return i, err
}

const listPendingVenueClaims = `-- name: ListPendingVenueClaims :many
SELECT id, clerk_id, venue_id, venue_name, address, city, state, zip, latitude, longitude, contact_name, contact_email, booking_email, message, status, submitted_at, reviewed_at, reviewed_by, review_notes FROM venue_claims
WHERE status = 'pending'
ORDER BY submitted_at ASC
`

func (q *Queries) ListPendingVenueClaims(ctx context.Context) ([]VenueClaim, error) {
	rows, err := q.db.Query(ctx, listPendingVenueClaims)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VenueClaim
	for rows.Next() {
		var i VenueClaim
		if err := rows.Scan(
			&i.ID,
			&i.ClerkID,
			&i.VenueID,
			&i.VenueName,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Latitude,
			&i.Longitude,
			&i.ContactName,
			&i.ContactEmail,
			&i.BookingEmail,
			&i.Message,
			&i.Status,
			&i.SubmittedAt,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.ReviewNotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVenueClaimsByClerkID = `-- name: ListVenueClaimsByClerkID :many
SELECT id, clerk_id, venue_id, venue_name, address, city, state, zip, latitude, longitude, contact_name, contact_email, booking_email, message, status, submitted_at, reviewed_at, reviewed_by, review_notes FROM venue_claims
WHERE clerk_id = $1
ORDER BY submitted_at DESC
`

func (q *Queries) ListVenueClaimsByClerkID(ctx context.Context, clerkID string) ([]VenueClaim, error) {
	rows, err := q.db.Query(ctx, listVenueClaimsByClerkID, clerkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VenueClaim
	for rows.Next() {
		var i VenueClaim
		if err := rows.Scan(
			&i.ID,
			&i.ClerkID,
			&i.VenueID,
			&i.VenueName,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Latitude,
			&i.Longitude,
			&i.ContactName,
			&i.ContactEmail,
			&i.BookingEmail,
			&i.Message,
			&i.Status,
			&i.SubmittedAt,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.ReviewNotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectVenueClaim = `-- name: RejectVenueClaim :one
UPDATE venue_claims SET
    status = 'rejected',
    reviewed_at = NOW(),
    reviewed_by = $2,
    review_notes = $3
WHERE id = $1
RETURNING id, clerk_id, venue_id, venue_name, address, city, state, zip, latitude, longitude, contact_name, contact_email, booking_email, message, status, submitted_at, reviewed_at, reviewed_by, review_notes
`

type RejectVenueClaimParams struct {
	ID          pgtype.UUID
	ReviewedBy  pgtype.Text
	ReviewNotes pgtype.Text
}

func (q *Queries) RejectVenueClaim(ctx context.Context, arg RejectVenueClaimParams) (VenueClaim, error) {
	row := q.db.QueryRow(ctx, rejectVenueClaim, arg.ID, arg.ReviewedBy, arg.ReviewNotes)
	var i VenueClaim
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.VenueID,
		&i.VenueName,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.ContactName,
		&i.ContactEmail,
		&i.BookingEmail,
		&i.Message,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.ReviewNotes,
	)
	return i, err
}
