// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: venues.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVenue = `-- name: CreateVenue :one
INSERT INTO venues (name, address, city, state, zip, latitude, longitude, hours, description)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, address, city, state, zip, latitude, longitude, hours, description, created_at, updated_at
`

type CreateVenueParams struct {
	Name        string
	Address     pgtype.Text
	City        pgtype.Text
	State       pgtype.Text
	Zip         pgtype.Text
	Latitude    float64
	Longitude   float64
	Hours       pgtype.Text
	Description pgtype.Text
}

func (q *Queries) CreateVenue(ctx context.Context, arg CreateVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, createVenue,
		arg.Name,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Latitude,
		arg.Longitude,
		arg.Hours,
		arg.Description,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.Hours,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVenue = `-- name: GetVenue :one
SELECT id, name, address, city, state, zip, latitude, longitude, hours, description, created_at, updated_at FROM venues WHERE id = $1
`

func (q *Queries) GetVenue(ctx context.Context, id pgtype.UUID) (Venue, error) {
	row := q.db.QueryRow(ctx, getVenue, id)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.Hours,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVenuesByLocation = `-- name: ListVenuesByLocation :many
SELECT id, name, address, city, state, zip, latitude, longitude, hours, description, created_at, updated_at
FROM venues
WHERE ST_DWithin(
    ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography,
    ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326)::geography,
    $3::float
)
ORDER BY name ASC
`

type ListVenuesByLocationParams struct {
	Lng          float64
	Lat          float64
	RadiusMeters float64
}

func (q *Queries) ListVenuesByLocation(ctx context.Context, arg ListVenuesByLocationParams) ([]Venue, error) {
	rows, err := q.db.Query(ctx, listVenuesByLocation, arg.Lng, arg.Lat, arg.RadiusMeters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Venue
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Latitude,
			&i.Longitude,
			&i.Hours,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVenue = `-- name: UpdateVenue :one
UPDATE venues SET
    name = $2,
    address = $3,
    city = $4,
    state = $5,
    zip = $6,
    latitude = $7,
    longitude = $8,
    hours = $9,
    description = $10,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, address, city, state, zip, latitude, longitude, hours, description, created_at, updated_at
`

type UpdateVenueParams struct {
	ID          pgtype.UUID
	Name        string
	Address     pgtype.Text
	City        pgtype.Text
	State       pgtype.Text
	Zip         pgtype.Text
	Latitude    float64
	Longitude   float64
	Hours       pgtype.Text
	Description pgtype.Text
}

func (q *Queries) UpdateVenue(ctx context.Context, arg UpdateVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, updateVenue,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Latitude,
		arg.Longitude,
		arg.Hours,
		arg.Description,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.Hours,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertVenue = `-- name: UpsertVenue :one
INSERT INTO venues (name, address, city, state, zip, latitude, longitude)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (LOWER(TRIM(name)), COALESCE(NULLIF(LOWER(TRIM(address)), ''), latitude::text || ',' || longitude::text))
DO UPDATE SET
    address = COALESCE(NULLIF(EXCLUDED.address, ''), venues.address),
    city = COALESCE(NULLIF(EXCLUDED.city, ''), venues.city),
    state = COALESCE(NULLIF(EXCLUDED.state, ''), venues.state),
    zip = COALESCE(NULLIF(EXCLUDED.zip, ''), venues.zip),
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    updated_at = NOW()
RETURNING id, name, address, city, state, zip, latitude, longitude, hours, description, created_at, updated_at
`

type UpsertVenueParams struct {
	Name      string
	Address   pgtype.Text
	City      pgtype.Text
	State     pgtype.Text
	Zip       pgtype.Text
	Latitude  float64
	Longitude float64
}

func (q *Queries) UpsertVenue(ctx context.Context, arg UpsertVenueParams) (Venue, error) {
	row := q.db.QueryRow(ctx, upsertVenue,
		arg.Name,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Latitude,
		arg.Longitude,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.Hours,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
